import { StorageObject } from '@microsoft/rayfin-core/experimental';
import { describe, expectTypeOf, it } from 'vitest';

import type { StorageClient, StorageObjectRef, UploadOptions } from '../index';

interface TeamDocument {
  team_id: string;
  transcription?: string;
}

describe('storage upload field types', () => {
  it('derives upload fields from the folder schema', () => {
    type Options = UploadOptions<StorageObjectRef & Partial<TeamDocument>>;

    expectTypeOf<NonNullable<Options['fields']>>().toEqualTypeOf<{
      team_id?: string;
      transcription?: string;
    }>();

    const validOptions: Options = {
      fields: {
        team_id: 'team-42',
        transcription: 'Meeting notes',
      },
    };
    expectTypeOf(validOptions).toExtend<Options>();

    const callerCorrelationId: Options = {
      // @ts-expect-error - correlation IDs are generated by the SDK
      correlationId: 'caller-id',
    };
    const perCallConflict: Options = {
      // @ts-expect-error - conflict behavior is configured on the folder
      onConflict: 'overwrite',
    };
    const progressCallback: Options = {
      // @ts-expect-error - progress callbacks are not part of upload options
      onProgress: () => undefined,
    };
    const freeFormMetadata: Options = {
      // @ts-expect-error - use typed fields instead of free-form metadata
      userMetadata: { source: 'test' },
    };
    expectTypeOf(callerCorrelationId).toExtend<Options>();
    expectTypeOf(perCallConflict).toExtend<Options>();
    expectTypeOf(progressCallback).toExtend<Options>();
    expectTypeOf(freeFormMetadata).toExtend<Options>();

    const unknownField: Options = {
      fields: {
        // @ts-expect-error - fields must be declared on the folder schema
        owner_id: 'user-42',
      },
    };
    expectTypeOf(unknownField).toExtend<Options>();

    const wrongFieldType: Options = {
      fields: {
        // @ts-expect-error - field values must match the folder schema
        team_id: 42,
      },
    };
    expectTypeOf(wrongFieldType).toExtend<Options>();
  });

  it('threads the folder schema through StorageClient.upload', () => {
    type Client = StorageClient<{ 'team-documents': TeamDocument }>;
    type Options = NonNullable<
      Parameters<Client['team-documents']['upload']>[2]
    >;

    expectTypeOf<NonNullable<Options['fields']>>().toEqualTypeOf<{
      team_id?: string;
      transcription?: string;
    }>();
  });

  it('returns optional typed custom fields on each storage object', () => {
    class TeamDocumentWithPolicyIntrinsics extends StorageObject {
      declare team_id: string;
      declare transcription?: string;
    }

    type Client = StorageClient<{
      'team-documents': TeamDocumentWithPolicyIntrinsics;
    }>;
    type FolderClient = Client['team-documents'];
    type Options = NonNullable<Parameters<FolderClient['upload']>[2]>;
    type ListItem = Awaited<ReturnType<FolderClient['list']>>['items'][number];

    expectTypeOf<NonNullable<Options['fields']>>().toEqualTypeOf<{
      team_id?: string;
      transcription?: string;
    }>();
    expectTypeOf<ListItem['team_id']>().toEqualTypeOf<string | undefined>();
    expectTypeOf<ListItem['transcription']>().toEqualTypeOf<
      string | undefined
    >();
    expectTypeOf<ListItem>().not.toHaveProperty('owner_id');
    expectTypeOf<ListItem>().not.toHaveProperty('content_type');
  });

  it('derives the same custom fields without extending StorageObject', () => {
    type Client = StorageClient<{ 'team-documents': TeamDocument }>;
    type FolderClient = Client['team-documents'];
    type Options = NonNullable<Parameters<FolderClient['upload']>[2]>;
    type ListItem = Awaited<ReturnType<FolderClient['list']>>['items'][number];

    expectTypeOf<NonNullable<Options['fields']>>().toEqualTypeOf<{
      team_id?: string;
      transcription?: string;
    }>();
    expectTypeOf<ListItem['team_id']>().toEqualTypeOf<string | undefined>();
  });
});
