/**
 * Compile-time `AutoGenerated<T>` marker and the type-level machinery that
 * detects and unwraps it.
 *
 * A column the database fills in — an `IDENTITY`, any `DEFAULT` (literal or
 * expression), or a computed (`AS (...)`) column — is annotated
 * `AutoGenerated<T>` on the connector entity. The marker is purely a
 * compile-time signal: it is erased at runtime (it is just `T` under the hood),
 * and the runtime companion signal is the presence of a `default` option on the
 * field decorator (see the field decorators + analyzer).
 *
 * Its job is to let the connector client give the right answer in the right
 * place: a marked column is **optional** on create and update, and **reads back
 * as plain `T`**. The brand is a required, type-only unique-symbol tag that
 * distinguishes a marked column from a plain one.
 */

/**
 * Type-only brand key. `declare const` means it never exists at runtime, so
 * `AutoGenerated<T>` adds no runtime footprint.
 *
 * @internal
 */
declare const autoGeneratedBrand: unique symbol;

/**
 * The phantom tag intersected into a marked column's type. The payload carries
 * the underlying `T` so {@link UnwrapAutoGenerated} can recover it.
 *
 * @internal
 */
export interface AutoGeneratedTag<out T> {
  readonly [autoGeneratedBrand]: T;
}

/**
 * Marks a column the database generates or computes.
 *
 * `AutoGenerated<T>` is `T` intersected with a required, type-only brand: a
 * value of the branded type is usable as a plain `T`, while a plain `T` is not
 * assignable to the branded type. Nullability is expressed on the property
 * itself (an optional `?` property or `optional: true`), never inside the
 * marker: always wrap the non-null base type — `AutoGenerated<number>`, not
 * `AutoGenerated<number | null>`.
 *
 * @typeParam T - The underlying column type (`number`, `string`, `Date`, …).
 */
export type AutoGenerated<T> = T & AutoGeneratedTag<T>;

/** Recover the underlying `T` from a (possibly) branded column type. */
export type UnwrapAutoGenerated<T> =
  T extends AutoGeneratedTag<infer U> ? U : T;

/**
 * `true` when `T` is an `AutoGenerated<…>` column, `false` otherwise.
 *
 * Fail-closed: `any` is not treated as generated; a nullable branded type
 * (`AutoGenerated<T> | null`) is detected via `NonNullable` (used only for
 * detection, never for output, so a legitimate `null` member is preserved); a
 * mixed union that is only partly branded
 * (e.g. `AutoGenerated<number> | string`) is deliberately *not* detected.
 */
export type IsAutoGenerated<T> =
  // `0 extends 1 & T` is `true` only for `any`, guarding against it.
  0 extends 1 & T
    ? false
    : [NonNullable<T>] extends [never]
      ? false
      : [NonNullable<T>] extends [AutoGeneratedTag<unknown>]
        ? true
        : false;

/**
 * The subset of `R`'s keys whose value is `AutoGenerated<…>`. `-?` strips the
 * optional modifier while probing so an already-optional marked property is
 * still classified (its value would otherwise include `undefined`).
 */
export type AutoGeneratedKeys<R> = {
  [K in keyof R]-?: IsAutoGenerated<R[K]> extends true ? K : never;
}[keyof R];

/**
 * A record with every `AutoGenerated<…>` column unwrapped to plain `T`.
 * Property modifiers are preserved — the read boundary relies on the entity
 * author using definite-assignment (`x!: AutoGenerated<T>`) so a non-null
 * generated column does not read back as `T | undefined`.
 */
export type ReadRecord<R> = {
  [K in keyof R]: UnwrapAutoGenerated<R[K]>;
};
