/**
 * Ultra-simplified decorator example - Todo application
 *
 * This demonstrates the type-specific decorator system that uses runtime metadata
 * for configuration generation. Compare this to the old verbose decorator system!
 *
 * Key improvements:
 * - 75% less code required
 * - Runtime metadata via TC39 Stage 3 decorators (Symbol.metadata)
 * - Type-specific decorators for explicit field types
 * - Composable constraint decorators (`@id`, `@unique`, `@optional`)
 */

import {
  entity,
  uuid,
  text,
  boolean,
  date,
  one,
  many,
  role,
} from '../../../decorators/decorators';

// Note: @dataSource and @runtime decorators are no longer needed!
// Configuration is generated by the CLI tool from runtime metadata.
// Database dialect and connection details are specified via CLI parameters.

@entity()
@role('anonymous', 'read')
@role('authenticated', ['create', 'read', 'update', 'delete'])
export class Todo {
  @uuid()
  id!: string; // UUID primary key, auto-inferred from 'id' name

  @text({ unique: true })
  slug!: string; // NVARCHAR(100), not null, unique constraint

  @text()
  title!: string; // NVARCHAR(255), not null (required by default)

  @text()
  description?: string; // NVARCHAR(MAX), required in DB, optional in TS

  @boolean()
  isCompleted!: boolean; // BIT, not null

  @text()
  priority!: 'low' | 'medium' | 'high'; // NVARCHAR(50) + check constraint

  @date()
  dueDate?: Date; // DATETIME2, required in DB, optional in TS

  @text()
  user_id!: string; // UNIQUEIDENTIFIER, not null - populated from JWT claims, not a FK

  @date()
  createdAt!: Date; // DATETIME2, not null

  @date()
  updatedAt!: Date; // DATETIME2, not null

  @one(() => Category)
  category!: Category; // Auto: many-to-one relationship + generates category_id FK
}

@entity()
@role('authenticated', '*')
export class Category {
  @uuid()
  id!: string; // UUID PK, auto-inferred from 'id' name

  @text({ unique: true })
  name!: string; // NVARCHAR(255), not null, unique constraint

  @text()
  color?: string; // NVARCHAR(255), required in DB, optional in TS

  @many(() => Todo)
  todos!: Todo[]; // Auto: one-to-many relationship (reverse side)
}

// Note: User entity is managed by Rayfin's authentication system in the control plane
// Todo items are associated with users via user_id field populated from JWT claims
@entity()
@role('authenticated', '*')
export class User {
  @uuid()
  id!: string; // UUID PK, auto-inferred from 'id' name

  @text({ unique: true })
  email!: string; // NVARCHAR(255), not null, unique constraint

  @text()
  name!: string; // NVARCHAR(255), not null

  @many(() => Todo)
  assignedTodos!: Todo[]; // Auto: one-to-many relationship
}

// Example of entity with uuid id
@entity()
export class ProjectTask {
  @uuid()
  id!: string; // PK auto-inferred from 'id' name

  @text()
  title!: string;

  @text()
  status!: 'pending' | 'in-progress' | 'completed' | 'cancelled'; // Auto: check constraint
}

/**
 * Generated SQL Schema (MSSQL):
 *
 * CREATE TABLE todos (
 *   id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
 *   slug NVARCHAR(100) NOT NULL UNIQUE,
 *   title NVARCHAR(255) NOT NULL,
 *   description NVARCHAR(MAX) NULL,
 *   isCompleted BIT NOT NULL,
 *   priority NVARCHAR(50) NOT NULL CHECK (priority IN ('low', 'medium', 'high')),
 *   dueDate DATETIME2 NULL,
 *   user_id UNIQUEIDENTIFIER NOT NULL, -- Populated from JWT claims, not a FK
 *   createdAt DATETIME2 NOT NULL,
 *   updatedAt DATETIME2 NOT NULL,
 *   category_id UNIQUEIDENTIFIER NOT NULL,
 *   FOREIGN KEY (category_id) REFERENCES categories(id)
 * );
 *
 * CREATE TABLE categories (
 *   id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
 *   name NVARCHAR(255) NOT NULL UNIQUE,
 *   color NVARCHAR(255) NULL
 * );
 *
 * -- Note: Users are managed in the control plane PostgreSQL database
 * -- and referenced via user_id populated from JWT token claims
 *
 * CREATE TABLE project_tasks (
 *   id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
 *   title NVARCHAR(255) NOT NULL,
 *   status NVARCHAR(50) NOT NULL CHECK (status IN ('pending', 'in-progress', 'completed', 'cancelled'))
 * );
 *
 * Generated DAB Configuration:
 * - Entities: todo, category, project-task
 * - Relationships: Auto-detected with proper cardinality
 * - Permissions: Role-based as specified
 * - X-Schema: Complete database metadata for each entity
 * - User association: Via user_id field populated from JWT claims
 *
 * CLI Usage:
 * rayfin generate src/ --dialect mssql --output dab-config.json
 */
