import { existsSync, readFileSync } from 'fs';
import { dirname, join, relative } from 'path';

import type { ConnectorEntry } from '@microsoft/rayfin-tools-common/_internal/config';
import {
  CONNECTOR_CATALOG,
  isValidConnectorName,
} from '@microsoft/rayfin-tools-common/_internal/config';
import { globSync } from 'glob';
import ts from 'typescript';

import { writeFileAtomic } from '../utils/atomic-write.js';
import { modeLog, modeWarn, type OutputMode } from '../utils/output-mode.js';

/**
 * App-side file that maps connector names to their config and runtime.
 *
 * `createConnectorsApi` throws `UNKNOWN_CONNECTOR` when a name is missing from
 * `connectorConfigs`, but a name missing from `connectorRuntimes` fails
 * silently — the transport's raw payload is handed to the app undecoded. For
 * connectors that return Apache Arrow that means the app renders nothing with
 * no error, so keeping this file in sync with `rayfin.yml` is load-bearing.
 */
const APP_WIRING_RELATIVE = 'src/lib/connectors.ts';

/** Marks a wiring file the CLI owns and may safely rewrite. */
const GENERATED_MARKER = '@generated by `rayfin connector add`';

/**
 * Types used by the generated wiring. It ships transitively under
 * `@microsoft/rayfin-client`, but strict resolvers (pnpm) treat an undeclared
 * transitive as a phantom dependency, so the app must declare it directly.
 */
const CONNECTORS_PACKAGE = '@microsoft/rayfin-connectors';

/**
 * A connector only lands in the wiring once its `schema.ts` actually exports a
 * `connectorConfig` value. Function-bridge scaffolds export one immediately;
 * SQL-style connectors ship a placeholder until entities are generated from
 * `metadata.json`. Keying off the real export means we never emit an import
 * that fails to compile, and connectors join the wiring automatically once
 * their schema is filled in.
 *
 * Anchored to the start of a line so a commented-out or quoted occurrence
 * (a `// export const connectorConfig` line) is not mistaken for a real export;
 * importing a symbol that does not exist would break the app's build.
 */
const CONFIG_EXPORT_PATTERN = /^\s*export\s+const\s+connectorConfig\b/m;

/**
 * Pristine template shape: both maps declared and empty. Anchored for the same
 * reason as {@link CONFIG_EXPORT_PATTERN} — a mention inside a comment must not
 * make a hand-written file look safe to overwrite.
 */
const EMPTY_CONFIGS_PATTERN =
  /^export\s+const\s+connectorConfigs[^=]*=\s*\{\s*\}/m;
const EMPTY_RUNTIMES_PATTERN =
  /^export\s+const\s+connectorRuntimes[^=]*=\s*\{\s*\}/m;

/**
 * Fences the part of `src/lib/connectors.ts` the app owns.
 *
 * The template ships more than the two maps: a copyright header, and an
 * `AppConnectorsSchema` type that `src/lib/rayfin-client.ts` imports. Rewriting
 * the file wholesale would delete both and turn a silently blank app into one
 * that does not compile, so everything above the first `connectorConfigs`
 * declaration is copied forward verbatim inside these fences. Fencing it (rather
 * than re-deriving it each run) keeps regeneration idempotent and lets imports
 * for a removed connector fall away, because only the fenced block survives.
 */
const PRESERVE_BEGIN = '// #region rayfin:app-owned';
const PRESERVE_END = '// #endregion rayfin:app-owned';

/** Start of the generated section: the first map declaration in the file. */
const CONFIGS_DECL_PATTERN = /^export\s+const\s+connectorConfigs\b/m;

/**
 * A doc comment with nothing after it. In the pristine template this is the
 * `connectorConfigs` JSDoc, which documents a map the CLI is about to generate
 * and whose worked example would contradict it. Anything earlier is left alone.
 */
const TRAILING_DOC_PATTERN = /\/\*\*(?:(?!\*\/)[\s\S])*?\*\/\s*$/;

/** Named bindings of an import statement, ignoring the module specifier. */
const IMPORT_BINDINGS_PATTERN = /import\s+(?:type\s+)?\{([^}]*)\}\s*from/g;

export type AppWiringAction =
  /** The CLI wrote the file. */
  | 'written'
  /** The file was already byte-identical to what the CLI would write. */
  | 'unchanged'
  /** The file is hand-owned; the caller must print `snippet` for the Builder. */
  | 'manual'
  /** No app or workspace package contains `src/lib/connectors.ts`. */
  | 'absent'
  /** More than one workspace package owns connector wiring. */
  | 'ambiguous';

export interface ConnectorWiringResult {
  /** Connector names included in the generated maps. */
  wired: string[];
  /** Connectors declared in `rayfin.yml` but not yet wireable, with reasons. */
  skipped: { name: string; reason: string }[];
  /** Connector names that also got a runtime entry. */
  runtimes: string[];
  action: AppWiringAction;
  /** Project-relative path to the resolved wiring file. */
  wiringPath?: string;
  /** Candidate wiring files when workspace ownership is ambiguous. */
  candidates?: string[];
  /** Populated when `action === 'manual'`: the exact file the Builder needs. */
  snippet?: string;
}

/** camelCase a connector name so it is usable as a TS identifier. */
function camelCaseIdentifier(name: string): string {
  const parts = name.split(/[^a-zA-Z0-9]+/).filter((p) => p.length > 0);
  if (parts.length === 0) return 'connector';
  const [first, ...rest] = parts;
  const head = /^[0-9]/.test(first) ? `c${first}` : first;
  return (
    head[0].toLowerCase() +
    head.slice(1) +
    rest.map((p) => p[0].toUpperCase() + p.slice(1)).join('')
  );
}

export interface WireablePlan {
  name: string;
  /** Local alias for the connector's `connectorConfig` export. */
  configAlias: string;
  /** Exported connector marker type and its local alias. */
  schemaType?: string;
  schemaAlias?: string;
  /** The schema type import already exists in the app-owned prologue. */
  schemaAlreadyImported?: boolean;
  /** Import path from the resolved app wiring file to the schema module. */
  schemaImportPath?: string;
  runtime?: { factory: string; package: string };
}

/** PascalCase a connector name for its generated `<Name>Schema` export. */
function pascalCaseIdentifier(name: string): string {
  return name
    .split(/[^a-zA-Z0-9]+/)
    .filter((part) => part.length > 0)
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join('');
}

interface ExistingSchemaBinding {
  exportedName: string;
  localName: string;
  alreadyImported: boolean;
}

/** Type aliases and interfaces this schema module actually exports. */
function exportedSchemaTypes(contents: string): Set<string> {
  const sourceFile = ts.createSourceFile(
    'schema.ts',
    contents,
    ts.ScriptTarget.Latest,
    true,
    ts.ScriptKind.TS
  );
  const exported = new Set<string>();
  for (const statement of sourceFile.statements) {
    if (
      (ts.isTypeAliasDeclaration(statement) ||
        ts.isInterfaceDeclaration(statement)) &&
      statement.modifiers?.some(
        (modifier) => modifier.kind === ts.SyntaxKind.ExportKeyword
      ) &&
      !statement.modifiers.some(
        (modifier) => modifier.kind === ts.SyntaxKind.DefaultKeyword
      )
    ) {
      exported.add(statement.name.text);
    }
  }
  return exported;
}

/** Existing app-owned connector-to-schema bindings that still resolve. */
function existingSchemaBindings(
  contents: string,
  prologue: string
): Map<string, ExistingSchemaBinding> {
  const sourceFile = ts.createSourceFile(
    APP_WIRING_RELATIVE,
    contents,
    ts.ScriptTarget.Latest,
    true,
    ts.ScriptKind.TS
  );
  const imports = new Map<
    string,
    { exportedName: string; modulePath: string }
  >();
  for (const statement of sourceFile.statements) {
    if (
      !ts.isImportDeclaration(statement) ||
      !ts.isStringLiteral(statement.moduleSpecifier) ||
      !statement.importClause?.namedBindings ||
      !ts.isNamedImports(statement.importClause.namedBindings)
    ) {
      continue;
    }
    for (const element of statement.importClause.namedBindings.elements) {
      imports.set(element.name.text, {
        exportedName: element.propertyName?.text ?? element.name.text,
        modulePath: statement.moduleSpecifier.text,
      });
    }
  }

  const bindings = new Map<string, ExistingSchemaBinding>();
  const preservedImports = importedBindings(prologue);
  const schema = sourceFile.statements.find(
    (statement): statement is ts.TypeAliasDeclaration =>
      ts.isTypeAliasDeclaration(statement) &&
      statement.name.text === 'AppConnectorsSchema'
  );
  if (!schema || !ts.isTypeLiteralNode(schema.type)) return bindings;

  for (const member of schema.type.members) {
    if (
      !ts.isPropertySignature(member) ||
      !member.type ||
      !ts.isTypeReferenceNode(member.type) ||
      !ts.isIdentifier(member.type.typeName)
    ) {
      continue;
    }
    const connectorName =
      member.name &&
      (ts.isStringLiteral(member.name) || ts.isIdentifier(member.name))
        ? member.name.text
        : undefined;
    if (!connectorName) continue;

    const localName = member.type.typeName.text;
    const imported = imports.get(localName);
    const moduleSuffix = `/rayfin/connectors/${connectorName}/schema`;
    if (
      imported &&
      (imported.modulePath.endsWith(moduleSuffix) ||
        imported.modulePath.endsWith(`${moduleSuffix}.js`))
    ) {
      bindings.set(connectorName, {
        exportedName: imported.exportedName,
        localName,
        alreadyImported: preservedImports.has(localName),
      });
    }
  }
  return bindings;
}

function schemaImportPath(appPath: string, schemaPath: string): string {
  const path = relative(
    dirname(appPath),
    schemaPath.replace(/\.ts$/u, '')
  ).replace(/\\/gu, '/');
  return path.startsWith('.') ? path : `./${path}`;
}

/**
 * Decide which declared connectors can be wired, and how.
 *
 * Skips are informational, not failures: a SQL connector whose entities have
 * not been generated yet is a normal intermediate state.
 */
function planWiring(
  projectRoot: string,
  connectors: readonly ConnectorEntry[],
  appPath: string,
  existingBindings: ReadonlyMap<string, ExistingSchemaBinding>
): {
  plans: WireablePlan[];
  skipped: { name: string; reason: string }[];
  manualRequired: boolean;
} {
  const plans: WireablePlan[] = [];
  const skipped: { name: string; reason: string }[] = [];
  const usedAliases = new Set<string>();
  const usedSchemaAliases = new Set<string>();
  let manualRequired = false;

  for (const entry of connectors) {
    // `rayfin.yml` is hand-editable, so a name reaches us unvalidated even
    // though `connector add` validates the one it just wrote. Names flow
    // straight into file paths, import specifiers, and quoted map keys, so an
    // unchecked one can escape its quotes and corrupt the generated file.
    if (!isValidConnectorName(entry.name)) {
      skipped.push({
        name: entry.name,
        reason: `"${entry.name}" is not a valid connector name (letters, digits, hyphens, and underscores only)`,
      });
      continue;
    }

    const schemaPath = join(
      projectRoot,
      'rayfin',
      'connectors',
      entry.name,
      'schema.ts'
    );
    if (!existsSync(schemaPath)) {
      skipped.push({
        name: entry.name,
        reason: `rayfin/connectors/${entry.name}/schema.ts is missing`,
      });
      continue;
    }

    let contents: string;
    try {
      contents = readFileSync(schemaPath, 'utf-8');
    } catch {
      skipped.push({
        name: entry.name,
        reason: `rayfin/connectors/${entry.name}/schema.ts could not be read`,
      });
      continue;
    }

    if (!CONFIG_EXPORT_PATTERN.test(contents)) {
      skipped.push({
        name: entry.name,
        reason: `rayfin/connectors/${entry.name}/schema.ts does not export \`connectorConfig\` yet`,
      });
      continue;
    }

    const exportedTypes = exportedSchemaTypes(contents);
    const expectedSchemaType = `${pascalCaseIdentifier(entry.name) || 'Connector'}Schema`;
    const existingBinding = existingBindings.get(entry.name);
    let schemaType: string;
    let schemaAlias: string;
    let schemaAlreadyImported = false;
    if (existingBinding && exportedTypes.has(existingBinding.exportedName)) {
      schemaType = existingBinding.exportedName;
      schemaAlias = existingBinding.localName;
      schemaAlreadyImported = existingBinding.alreadyImported;
    } else if (exportedTypes.has(expectedSchemaType)) {
      schemaType = expectedSchemaType;
      schemaAlias = `${camelCaseIdentifier(entry.name)}Schema`;
    } else if (exportedTypes.size === 1) {
      schemaType = [...exportedTypes][0];
      schemaAlias = `${camelCaseIdentifier(entry.name)}Schema`;
    } else {
      skipped.push({
        name: entry.name,
        reason: `rayfin/connectors/${entry.name}/schema.ts does not export an unambiguous connector schema type`,
      });
      manualRequired = true;
      continue;
    }

    // Aliases are derived from Builder-chosen names, so two distinct names can
    // collide once punctuation is stripped ("store-sales" / "store_sales").
    // Suffix on collision rather than silently emitting a duplicate binding.
    const base = `${camelCaseIdentifier(entry.name)}Config`;
    let alias = base;
    let suffix = 2;
    while (usedAliases.has(alias)) alias = `${base}${suffix++}`;
    usedAliases.add(alias);

    const schemaBase = schemaAlias;
    let schemaSuffix = 2;
    while (usedSchemaAliases.has(schemaAlias)) {
      if (schemaAlreadyImported) {
        skipped.push({
          name: entry.name,
          reason: `the app-owned schema alias ${schemaAlias} is already used by another connector`,
        });
        manualRequired = true;
        schemaAlias = '';
        break;
      }
      schemaAlias = `${schemaBase}${schemaSuffix++}`;
    }
    if (!schemaAlias) continue;
    usedSchemaAliases.add(schemaAlias);

    const meta = CONNECTOR_CATALOG[entry.type];
    plans.push({
      name: entry.name,
      configAlias: alias,
      schemaType,
      schemaAlias,
      schemaAlreadyImported,
      schemaImportPath: schemaImportPath(appPath, schemaPath),
      runtime: meta?.runtimeFactory
        ? {
            factory: meta.runtimeFactory.name,
            package: meta.runtimeFactory.package,
          }
        : undefined,
    });
  }

  return { plans, skipped, manualRequired };
}

/**
 * The app-owned block to carry forward into a regenerated wiring file.
 *
 * Three cases, in order. A file the CLI already fenced hands back exactly what
 * is inside the fence, which is what makes regeneration idempotent and lets a
 * removed connector's import disappear. A file with no generated marker is the
 * pristine template (or a Builder file the caller has already cleared as safe),
 * so everything above the first `connectorConfigs` declaration is app-owned.
 * Anything else was generated before fencing existed and has nothing to keep.
 */
export function extractAppOwnedPrologue(contents: string): string {
  const begin = contents.indexOf(PRESERVE_BEGIN);
  const end = contents.indexOf(PRESERVE_END);
  if (begin !== -1 && end > begin) {
    const bodyStart = contents.indexOf('\n', begin);
    if (bodyStart !== -1 && bodyStart < end) {
      return trimPrologue(contents.slice(bodyStart + 1, end));
    }
  }

  if (contents.includes(GENERATED_MARKER)) return '';

  const decl = CONFIGS_DECL_PATTERN.exec(contents);
  if (!decl) return '';
  return trimPrologue(contents.slice(0, decl.index));
}

/** Drop the doc comment that documented the map we are about to generate. */
function trimPrologue(block: string): string {
  const sourceFile = ts.createSourceFile(
    APP_WIRING_RELATIVE,
    block,
    ts.ScriptTarget.Latest,
    true,
    ts.ScriptKind.TS
  );
  const declarations = sourceFile.statements.filter(
    (statement): statement is ts.TypeAliasDeclaration =>
      ts.isTypeAliasDeclaration(statement) &&
      statement.name.text === 'AppConnectorsSchema'
  );
  const schemaReferences = new Set<string>();
  const collectSchemaReferences = (node: ts.Node): void => {
    if (ts.isIdentifier(node)) schemaReferences.add(node.text);
    ts.forEachChild(node, collectSchemaReferences);
  };
  for (const declaration of declarations) {
    if (!ts.isTypeLiteralNode(declaration.type)) {
      collectSchemaReferences(declaration.type);
    }
  }

  let withoutSchema = block;
  for (const declaration of declarations.reverse()) {
    const declarationStart = declaration.getStart(sourceFile);
    const leadingStart = declaration.getFullStart();
    const leadingTrivia = block.slice(leadingStart, declarationStart);
    const jsDoc = /\/\*\*(?:(?!\*\/)[\s\S])*?\*\/\s*$/u.exec(leadingTrivia);
    const start = jsDoc ? leadingStart + jsDoc.index : declarationStart;
    withoutSchema =
      withoutSchema.slice(0, start) + withoutSchema.slice(declaration.end);
  }

  const remainingSource = ts.createSourceFile(
    APP_WIRING_RELATIVE,
    withoutSchema,
    ts.ScriptTarget.Latest,
    true,
    ts.ScriptKind.TS
  );
  const remainingReferences = new Set<string>();
  const collectRemainingReferences = (node: ts.Node): void => {
    if (ts.isIdentifier(node)) remainingReferences.add(node.text);
    ts.forEachChild(node, collectRemainingReferences);
  };
  for (const statement of remainingSource.statements) {
    if (!ts.isImportDeclaration(statement)) {
      collectRemainingReferences(statement);
    }
  }

  const importEdits: Array<{
    start: number;
    end: number;
    replacement: string;
  }> = [];
  for (const statement of remainingSource.statements) {
    if (!ts.isImportDeclaration(statement)) continue;

    const importClause = statement.importClause;
    const namedBindings = importClause?.namedBindings;
    if (!namedBindings || !ts.isNamedImports(namedBindings)) continue;

    const retained = namedBindings.elements.filter(
      (element) =>
        !schemaReferences.has(element.name.text) ||
        remainingReferences.has(element.name.text)
    );
    if (retained.length === namedBindings.elements.length) continue;

    let replacement = '';
    if (retained.length > 0 || importClause.name) {
      const updatedBindings = ts.factory.updateNamedImports(
        namedBindings,
        retained
      );
      const updatedClause = ts.factory.updateImportClause(
        importClause,
        importClause.isTypeOnly,
        importClause.name,
        updatedBindings
      );
      const updatedImport = ts.factory.updateImportDeclaration(
        statement,
        statement.modifiers,
        updatedClause,
        statement.moduleSpecifier,
        statement.attributes
      );
      replacement = ts
        .createPrinter()
        .printNode(ts.EmitHint.Unspecified, updatedImport, remainingSource);
    }
    importEdits.push({
      start: statement.getStart(remainingSource),
      end: statement.end,
      replacement,
    });
  }
  for (const edit of importEdits.reverse()) {
    withoutSchema =
      withoutSchema.slice(0, edit.start) +
      edit.replacement +
      withoutSchema.slice(edit.end);
  }

  return withoutSchema
    .replace(TRAILING_DOC_PATTERN, '')
    .replace(/^\s+|\s+$/g, '');
}

/**
 * Local names an app-owned block already binds via named imports.
 *
 * Used to avoid re-declaring an identifier the prologue imports. Matching the
 * import statement (not the bare identifier) matters: the pristine template
 * mentions `ConnectorConfig` inside a JSDoc example, and a text search would
 * suppress an import the file genuinely needs.
 */
function importedBindings(source: string): Set<string> {
  const names = new Set<string>();
  for (const match of source.matchAll(IMPORT_BINDINGS_PATTERN)) {
    for (const raw of match[1].split(',')) {
      const local = raw
        .trim()
        .split(/\s+as\s+/)
        .pop()
        ?.trim()
        .replace(/^type\s+/, '');
      if (local) names.add(local);
    }
  }
  return names;
}

/**
 * Render the full contents of `src/lib/connectors.ts` for `plans`.
 *
 * `prologue` is the app-owned block from {@link extractAppOwnedPrologue}. It is
 * emitted verbatim above the generated section, and any identifier it already
 * imports is left out of the generated imports.
 */
export function renderAppWiring(
  plans: readonly WireablePlan[],
  prologue = ''
): string {
  const runtimePackages = [
    ...new Set(
      plans
        .filter((p) => p.runtime)
        .map((p) => `${p.runtime!.package}::${p.runtime!.factory}`)
    ),
  ].sort();

  const bound = prologue ? importedBindings(prologue) : new Set<string>();
  const lines: string[] = [];

  if (prologue) {
    lines.push(
      `${PRESERVE_BEGIN} — copied verbatim by the Rayfin CLI; edit freely.`,
      prologue,
      PRESERVE_END,
      ``
    );
  }

  lines.push(
    `// ${GENERATED_MARKER} — do not edit below this line.`,
    `//`,
    `// Regenerated from rayfin.yml on every \`rayfin connector add\` and`,
    `// \`rayfin connector remove\`. To take ownership of this file, delete the`,
    `// line above; the CLI will then print the required wiring instead of`,
    `// rewriting it.`,
    ``
  );

  for (const spec of runtimePackages) {
    const [pkg, factory] = spec.split('::');
    if (bound.has(factory)) continue;
    lines.push(`import { ${factory} } from '${pkg}';`);
  }

  const typeImports = ['ConnectorConfig', 'ConnectorsRuntime'].filter(
    (name) => !bound.has(name)
  );
  if (typeImports.length > 0) {
    lines.push(`import type {`);
    for (const name of typeImports) lines.push(`  ${name},`);
    lines.push(`} from '${CONNECTORS_PACKAGE}';`);
  }
  lines.push(``);

  for (const plan of plans) {
    const schemaType =
      plan.schemaType ??
      `${pascalCaseIdentifier(plan.name) || 'Connector'}Schema`;
    const schemaAlias =
      plan.schemaAlias ?? `${camelCaseIdentifier(plan.name)}Schema`;
    const schemaBinding = plan.schemaAlreadyImported
      ? ''
      : schemaType === schemaAlias
        ? `, type ${schemaType}`
        : `, type ${schemaType} as ${schemaAlias}`;
    lines.push(
      `import { connectorConfig as ${plan.configAlias}${schemaBinding} } from '${plan.schemaImportPath ?? `../../rayfin/connectors/${plan.name}/schema`}';`
    );
  }
  if (plans.length > 0) lines.push(``);

  if (plans.length === 0) {
    lines.push(`export type AppConnectorsSchema = Record<string, never>;`, ``);
  } else {
    lines.push(`export type AppConnectorsSchema = {`);
    for (const plan of plans) {
      const schemaAlias =
        plan.schemaAlias ?? `${camelCaseIdentifier(plan.name)}Schema`;
      lines.push(`  '${plan.name}': ${schemaAlias};`);
    }
    lines.push(`};`, ``);
  }

  if (plans.length === 0) {
    lines.push(
      `export const connectorConfigs: Record<string, ConnectorConfig> = {};`,
      ``,
      `export const connectorRuntimes: ConnectorsRuntime = {};`,
      ``
    );
    return lines.join('\n');
  }

  lines.push(
    `export const connectorConfigs: Record<string, ConnectorConfig> = {`
  );
  for (const plan of plans) {
    lines.push(`  '${plan.name}': ${plan.configAlias},`);
  }
  lines.push(`};`, ``);

  const withRuntime = plans.filter((p) => p.runtime);
  if (withRuntime.length === 0) {
    lines.push(
      `// No declared connector ships a client-side runtime, so every operation`,
      `// uses the default JSON pass-through.`,
      `export const connectorRuntimes: ConnectorsRuntime = {};`,
      ``
    );
  } else {
    lines.push(`export const connectorRuntimes: ConnectorsRuntime = {`);
    for (const plan of withRuntime) {
      // Factories take no arguments — the connector target is resolved
      // server-side from rayfin.yml, never from client code.
      lines.push(`  '${plan.name}': ${plan.runtime!.factory}(),`);
    }
    lines.push(`};`, ``);
  }

  return lines.join('\n');
}

/**
 * Decide whether the CLI may rewrite an existing `src/lib/connectors.ts`.
 *
 * Two cases are safe: a file the CLI previously generated, and the pristine
 * template shape (both maps present and empty), which has nothing to lose.
 * Anything else is Builder-owned and is never clobbered.
 */
function isSafeToRewrite(contents: string): boolean {
  if (contents.includes(GENERATED_MARKER)) return true;
  return (
    EMPTY_CONFIGS_PATTERN.test(contents) &&
    EMPTY_RUNTIMES_PATTERN.test(contents)
  );
}

function workspacePatterns(packageJson: unknown): string[] {
  if (!packageJson || typeof packageJson !== 'object') return [];
  const workspaces = (packageJson as { workspaces?: unknown }).workspaces;
  const configured = Array.isArray(workspaces)
    ? workspaces
    : workspaces &&
        typeof workspaces === 'object' &&
        Array.isArray((workspaces as { packages?: unknown }).packages)
      ? (workspaces as { packages: unknown[] }).packages
      : [];
  return configured.filter(
    (value): value is string => typeof value === 'string'
  );
}

function declaresConnectors(packageJson: unknown): boolean {
  if (!packageJson || typeof packageJson !== 'object') return false;
  const manifest = packageJson as Record<string, unknown>;
  return ['dependencies', 'devDependencies', 'peerDependencies'].some(
    (field) => {
      const dependencies = manifest[field];
      return (
        dependencies !== null &&
        typeof dependencies === 'object' &&
        CONNECTORS_PACKAGE in dependencies
      );
    }
  );
}

/** Resolve the one package that owns the app-side connector surface. */
function resolveAppWiring(projectRoot: string): {
  appPath?: string;
  relativePath?: string;
  candidates?: string[];
} {
  const rootManifestPath = join(projectRoot, 'package.json');
  let rootManifest: unknown;
  try {
    rootManifest = JSON.parse(readFileSync(rootManifestPath, 'utf-8'));
  } catch {
    const appPath = join(projectRoot, APP_WIRING_RELATIVE);
    return existsSync(appPath)
      ? { appPath, relativePath: APP_WIRING_RELATIVE }
      : {};
  }

  const manifests = new Set<string>([rootManifestPath]);
  const patterns = workspacePatterns(rootManifest).map(
    (pattern) => `${pattern.replace(/\/$/u, '')}/package.json`
  );
  if (patterns.length > 0) {
    for (const manifestPath of globSync(patterns, {
      cwd: projectRoot,
      absolute: true,
      nodir: true,
    })) {
      manifests.add(manifestPath);
    }
  }

  const candidates: { appPath: string; declaresPackage: boolean }[] = [];
  for (const manifestPath of manifests) {
    let manifest: unknown;
    try {
      manifest =
        manifestPath === rootManifestPath
          ? rootManifest
          : JSON.parse(readFileSync(manifestPath, 'utf-8'));
    } catch {
      continue;
    }
    const appPath = join(dirname(manifestPath), APP_WIRING_RELATIVE);
    if (existsSync(appPath)) {
      candidates.push({
        appPath,
        declaresPackage: declaresConnectors(manifest),
      });
    }
  }

  const preferred = candidates.filter((candidate) => candidate.declaresPackage);
  const eligible = preferred.length > 0 ? preferred : candidates;
  const relativeCandidates = eligible.map((candidate) =>
    relative(projectRoot, candidate.appPath).replace(/\\/gu, '/')
  );
  if (eligible.length === 1) {
    return {
      appPath: eligible[0].appPath,
      relativePath: relativeCandidates[0],
    };
  }
  return eligible.length > 1 ? { candidates: relativeCandidates } : {};
}

/**
 * Regenerate the app's connector wiring from the declared connectors.
 *
 * Called by both `connector add` and `connector remove` so the wiring is
 * always a pure function of `rayfin.yml` plus the on-disk connector schemas.
 * Never throws: a project with no root or workspace-owned wiring file reports
 * `absent`, and a Builder-owned file reports `manual` with the exact contents
 * they need. The caller owns all user-facing output.
 */
export function regenerateConnectorWiring(
  projectRoot: string,
  connectors: readonly ConnectorEntry[]
): ConnectorWiringResult {
  const location = resolveAppWiring(projectRoot);
  if (location.candidates) {
    return {
      wired: [],
      runtimes: [],
      skipped: [],
      action: 'ambiguous',
      candidates: location.candidates,
    };
  }
  if (!location.appPath || !location.relativePath) {
    const { plans, skipped } = planWiring(
      projectRoot,
      connectors,
      join(projectRoot, APP_WIRING_RELATIVE),
      new Map()
    );
    return {
      wired: plans.map((plan) => plan.name),
      runtimes: plans.filter((plan) => plan.runtime).map((plan) => plan.name),
      skipped,
      action: 'absent',
    };
  }

  const appPath = location.appPath;
  let current: string;
  try {
    current = readFileSync(appPath, 'utf-8');
  } catch {
    const { plans, skipped, manualRequired } = planWiring(
      projectRoot,
      connectors,
      appPath,
      new Map()
    );
    return {
      wired: plans.map((plan) => plan.name),
      runtimes: plans.filter((plan) => plan.runtime).map((plan) => plan.name),
      skipped,
      action: 'manual',
      wiringPath: location.relativePath,
      snippet: manualRequired ? undefined : renderAppWiring(plans),
    };
  }

  const prologue = extractAppOwnedPrologue(current);
  const { plans, skipped, manualRequired } = planWiring(
    projectRoot,
    connectors,
    appPath,
    existingSchemaBindings(current, prologue)
  );
  const base = {
    wired: plans.map((p) => p.name),
    runtimes: plans.filter((p) => p.runtime).map((p) => p.name),
    skipped,
    wiringPath: location.relativePath,
  };
  if (manualRequired) {
    return { ...base, action: 'manual' };
  }

  if (!isSafeToRewrite(current)) {
    // The snippet deliberately omits the app-owned prologue. The file belongs
    // to the Builder here, so echoing their own code back adds noise; only the
    // wiring they have to add is useful.
    return { ...base, action: 'manual', snippet: renderAppWiring(plans) };
  }

  const rendered = renderAppWiring(plans, prologue);
  if (current === rendered) {
    return { ...base, action: 'unchanged' };
  }

  try {
    // Atomic (temp file + rename) so an interrupted or failed write cannot
    // leave a truncated `connectors.ts` behind. A partially written wiring file
    // is strictly worse than an unwired one: it does not compile.
    writeFileAtomic(appPath, rendered);
  } catch {
    // A read-only or locked `connectors.ts` must not throw here: `rayfin.yml`
    // has already been written, so a raw stack trace would leave the Builder
    // with a half-applied add and no recovery hint. Fall back to `manual` and
    // hand them the exact contents we tried to write — re-rendering without the
    // prologue would drop the app-owned header and the `AppConnectorsSchema`
    // type the client imports.
    return { ...base, action: 'manual', snippet: rendered };
  }
  return { ...base, action: 'written' };
}

export { APP_WIRING_RELATIVE };

/**
 * Print the outcome of {@link regenerateConnectorWiring}.
 *
 * The bug this exists for is silence: `connector add` used to report success
 * while leaving the app unwired, so the app built, deployed, and rendered
 * nothing. Every outcome that leaves the app not fully wired is therefore
 * reported at normal verbosity — only the fully-successful and no-op cases
 * are quiet.
 */
export function reportConnectorWiring(
  mode: OutputMode,
  result: ConnectorWiringResult,
  verbose: boolean
): void {
  const wiringPath = result.wiringPath ?? APP_WIRING_RELATIVE;
  if (result.action === 'written') {
    const runtimeNote =
      result.runtimes.length > 0
        ? ` (${result.runtimes.length} with a client-side runtime)`
        : '';
    modeLog(
      mode,
      `🔌 Wired ${result.wired.length} connector(s) into ${wiringPath}${runtimeNote}`
    );
  } else if (result.action === 'unchanged') {
    if (verbose) {
      modeLog(mode, `   ${wiringPath} already up to date.`);
    }
  } else if (result.action === 'absent') {
    modeWarn(
      mode,
      `⚠️  No ${APP_WIRING_RELATIVE} in this project — nothing was wired.\n` +
        `   This app template does not use the connectorConfigs/connectorRuntimes\n` +
        `   surface, so the connector is registered in rayfin.yml only.`
    );
    // Per-connector skips describe why a connector missed a wiring file that
    // does not exist here. Printing them would contradict the line above.
    return;
  } else if (result.action === 'ambiguous') {
    modeWarn(
      mode,
      `⚠️  Multiple workspace packages own connector wiring — nothing was changed.\n` +
        `${(result.candidates ?? []).map((path) => `   ${path}`).join('\n')}\n` +
        `   Keep one connector consumer or update the intended file manually.`
    );
    return;
  } else if (result.snippet) {
    modeWarn(
      mode,
      `⚠️  ${wiringPath} has manual edits — not overwriting.\n` +
        `   The app reads its connectors from that file. Until it lists this\n` +
        `   connector the app will render nothing, with no error.\n` +
        `   Apply this content (or merge the maps into your version):\n\n` +
        `${result.snippet ?? ''}`
    );
  } else {
    modeWarn(
      mode,
      `⚠️  ${wiringPath} was left unchanged because its connector schema mapping could not be resolved safely.`
    );
  }

  for (const skip of result.skipped) {
    modeWarn(
      mode,
      `⚠️  Connector "${skip.name}" is not wired into ${wiringPath}: ${skip.reason}.\n` +
        `   Fix the cause above, then retry; or update ${wiringPath} manually.`
    );
  }
}
