/**
 * Raw `executeDaxQueries` Arrow responses captured from the Power BI service,
 * base64-encoded. Both come from literal-only DAX queries (no model data), so
 * they carry nothing but the synthetic values listed below.
 *
 * Power BI returns Variant results (a measure or expression whose type varies
 * per row) as LZ4-compressed, dictionary-encoded dense unions:
 * `Dictionary<Int8, Union<Int64 | Decimal[19e+4] | Bool | Date64<MILLISECOND> | Float64 | Utf8>>`.
 */

/**
 * `EVALUATE ADDCOLUMNS(GENERATESERIES(1, 2, 1), "m", IF([Value] = 1, 5, "text"))`
 *
 * Expected rows: `{ [Value]: 1, [m]: 5 }`, `{ [Value]: 2, [m]: 'text' }`.
 */
export const POWER_BI_VARIANT_INT_STRING =
  '/////2gCAAAUAAAAAAAAAAAACgAMAAYABQAIAAoAAAAAAQQABAAAAOj9//8EAAAAAgAAAOQBAAAU' +
  'AAAAEAAYAAgABgAHAAwAEAAUABAAAAAAAAEOLAAAAFwAAAA0AAAABAAAAAYAAABwAQAAIAEAAPAA' +
  'AADEAAAAjAAAAGAAAAADAAAAW21dAAgAEAAIAAQACAAAAAwAAAABAAAAAAAAAET+//8AAAABCAAA' +
  'AAgADAAGAAgACAAAAAAAAQAEAAAABgAAAAAAAAABAAAAAgAAAAMAAAAEAAAABQAAABT///8AAAEF' +
  'EAAAABgAAAAEAAAAAAAAAAYAAABzdHJpbmcAAHz///88////AAABAxAAAAAgAAAABAAAAAAAAAAG' +
  'AAAAZG91YmxlAAAAAAYACAAGAAYAAAAAAAIAcP///wAAAQgQAAAAGAAAAAQAAAAAAAAABAAAAGRh' +
  'dGUAAAAA2P///5j///8AAAEGEAAAABwAAAAEAAAAAAAAAAQAAABib29sAAAAAAQABAAEAAAAxP//' +
  '/wAAAQcQAAAAJAAAAAQAAAAAAAAACAAAAGN1cnJlbmN5AAAAAAgADAAEAAgACAAAABMAAAAEAAAA' +
  'EAAUAAgABgAHAAwAAAAQABAAAAAAAAECEAAAABgAAAAEAAAAAAAAAAUAAABpbnQ2NAAAAKD///8A' +
  'AAABQAAAABAAGAAIAAAABwAMABAAFAAQAAAAAAAAAhQAAABAAAAAIAAAAAQAAAAAAAAABwAAAFtW' +
  'YWx1ZV0ACAAIAAAABAAIAAAABAAAAPT///8AAAABCAAAAAgADAAIAAcACAAAAAAAAAFAAAAA////' +
  '/6gAAAAUAAAAAAAAAAwAGAAGAAUACAAMAAwAAAAAAgQAGAAAACgAAAAAAAAAAAAAAAgACAAAAAQA' +
  'CAAAABAAAAAMABwAEAAEAAgADAAMAAAASAAAABwAAAAUAAAAAgAAAAAAAAAAAAAABAAEAAQAAAAC' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJQAAAAAAAAAAAAAAAQAAAAIAAAAAAAAAAAAAAAAA' +
  'AAAQAAAAAAAAAAQiTRhgQIIOAAAAIgEAAQCAAgAAAAAAAAAAAAAAAAAA/////+ABAAAUAAAAAAAA' +
  'AAwAFAAGAAUACAAMAAwAAAAAAgQAFAAAAKAAAAAAAAAACAAUAAgABAAIAAAAHAAAAAEAAAAAAAAA' +
  'AAAAAAwAHAAQAAQACAAMAAwAAAAYAQAAHAAAABQAAAACAAAAAAAAAAAAAAAEAAQABAAAAA8AAAAA' +
  'AAAAAAAAABkAAAAAAAAAIAAAAAAAAAAfAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAB8A' +
  'AAAAAAAAYAAAAAAAAAAAAAAAAAAAAGAAAAAAAAAAAAAAAAAAAABgAAAAAAAAAAAAAAAAAAAAYAAA' +
  'AAAAAAAAAAAAAAAAAGAAAAAAAAAAAAAAAAAAAABgAAAAAAAAAAAAAAAAAAAAYAAAAAAAAAAAAAAA' +
  'AAAAAGAAAAAAAAAAAAAAAAAAAABgAAAAAAAAAAAAAAAAAAAAYAAAAAAAAAAfAAAAAAAAAIAAAAAA' +
  'AAAAGwAAAAAAAAAAAAAABwAAAAIAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAEAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAQiTRhgQIICAACAAAUAAAAAAAAAAAAAAAgAAAAAAAAA' +
  'BCJNGGBAgggAAIAAAAAAAAAAAAAAAAAACAAAAAAAAAAEIk0YYECCCAAAgAUAAAAAAAAAAAAAAAAI' +
  'AAAAAAAAAAQiTRhgQIIIAACAAAAAAAQAAAAAAAAAAAQAAAAAAAAABCJNGGBAggQAAIB0ZXh0AAAA' +
  'AAAAAAAA/////8gAAAAUAAAAAAAAAAwAGAAGAAUACAAMAAwAAAAAAwQAHAAAAEAAAAAAAAAAAAAA' +
  'AAwAHAAQAAQACAAMAAwAAABoAAAAHAAAABQAAAACAAAAAAAAAAAAAAAEAAQABAAAAAQAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAZAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAABkAAAAA' +
  'AAAAAAAAAAIAAAACAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAIAAAAAAAAABCJNGGBA' +
  'ggIAAIAAAQAAAAAAAAAAAAAAAgAAAAAAAAAEIk0YYECCAgAAgAABAAAAAAAAAAAAAAD/////AAAA' +
  'AA==';

/**
 * A literal-only query over `GENERATESERIES(1, 3, 1)` whose `[m]` column
 * yields `CURRENCY(12.34)`, `"text"`, and `DATE(2024, 1, 31)`.
 *
 * Expected `[m]` values: `12.34`, `'text'`, `'2024-01-31T00:00:00.000'`.
 */
export const POWER_BI_VARIANT_CURRENCY_STRING_DATE =
  '/////2gCAAAUAAAAAAAAAAAACgAMAAYABQAIAAoAAAAAAQQABAAAAOj9//8EAAAAAgAAAOQBAAAU' +
  'AAAAEAAYAAgABgAHAAwAEAAUABAAAAAAAAEOLAAAAFwAAAA0AAAABAAAAAYAAABwAQAAIAEAAPAA' +
  'AADEAAAAjAAAAGAAAAADAAAAW21dAAgAEAAIAAQACAAAAAwAAAABAAAAAAAAAET+//8AAAABCAAA' +
  'AAgADAAGAAgACAAAAAAAAQAEAAAABgAAAAAAAAABAAAAAgAAAAMAAAAEAAAABQAAABT///8AAAEF' +
  'EAAAABgAAAAEAAAAAAAAAAYAAABzdHJpbmcAAHz///88////AAABAxAAAAAgAAAABAAAAAAAAAAG' +
  'AAAAZG91YmxlAAAAAAYACAAGAAYAAAAAAAIAcP///wAAAQgQAAAAGAAAAAQAAAAAAAAABAAAAGRh' +
  'dGUAAAAA2P///5j///8AAAEGEAAAABwAAAAEAAAAAAAAAAQAAABib29sAAAAAAQABAAEAAAAxP//' +
  '/wAAAQcQAAAAJAAAAAQAAAAAAAAACAAAAGN1cnJlbmN5AAAAAAgADAAEAAgACAAAABMAAAAEAAAA' +
  'EAAUAAgABgAHAAwAAAAQABAAAAAAAAECEAAAABgAAAAEAAAAAAAAAAUAAABpbnQ2NAAAAKD///8A' +
  'AAABQAAAABAAGAAIAAAABwAMABAAFAAQAAAAAAAAAhQAAABAAAAAIAAAAAQAAAAAAAAABwAAAFtW' +
  'YWx1ZV0ACAAIAAAABAAIAAAABAAAAPT///8AAAABCAAAAAgADAAIAAcACAAAAAAAAAFAAAAA////' +
  '/6gAAAAUAAAAAAAAAAwAGAAGAAUACAAMAAwAAAAAAgQAGAAAADAAAAAAAAAAAAAAAAgACAAAAAQA' +
  'CAAAABAAAAAMABwAEAAEAAgADAAMAAAASAAAABwAAAAUAAAAAwAAAAAAAAAAAAAABAAEAAQAAAAC' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKgAAAAAAAAAAAAAAAQAAAAMAAAAAAAAAAAAAAAAA' +
  'AAAYAAAAAAAAAAQiTRhgQIITAAAAIgEAAQASAgcAkAADAAAAAAAAAAAAAAAAAAAAAAD/////4AEA' +
  'ABQAAAAAAAAADAAUAAYABQAIAAwADAAAAAACBAAUAAAA0AAAAAAAAAAIABQACAAEAAgAAAAcAAAA' +
  'AQAAAAAAAAAAAAAADAAcABAABAAIAAwADAAAABgBAAAcAAAAFAAAAAMAAAAAAAAAAAAAAAQABAAE' +
  'AAAADwAAAAAAAAAAAAAAGgAAAAAAAAAgAAAAAAAAACMAAAAAAAAASAAAAAAAAAAAAAAAAAAAAEgA' +
  'AAAAAAAAAAAAAAAAAABIAAAAAAAAAAAAAAAAAAAASAAAAAAAAAAkAAAAAAAAAHAAAAAAAAAAAAAA' +
  'AAAAAABwAAAAAAAAAAAAAAAAAAAAcAAAAAAAAAAAAAAAAAAAAHAAAAAAAAAAHwAAAAAAAACQAAAA' +
  'AAAAAAAAAAAAAAAAkAAAAAAAAAAAAAAAAAAAAJAAAAAAAAAAAAAAAAAAAACQAAAAAAAAAB8AAAAA' +
  'AAAAsAAAAAAAAAAbAAAAAAAAAAAAAAAHAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAMAAAAAAAAABCJNGGBAggMAAIABBQMAAAAAAAAAAAAA' +
  'DAAAAAAAAAAEIk0YYECCDAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAABCJNGGBAgg0A' +
  'AABDCOIBAAEAUAAAAAAAAAAAAAAAAAAIAAAAAAAAAAQiTRhgQIIIAACAALzQXI0BAAAAAAAAAAgA' +
  'AAAAAAAABCJNGGBAgggAAIAAAAAABAAAAAAAAAAABAAAAAAAAAAEIk0YYECCBAAAgHRleHQAAAAA' +
  'AAAAAAD/////yAAAABQAAAAAAAAADAAYAAYABQAIAAwADAAAAAADBAAcAAAAQAAAAAAAAAAAAAAA' +
  'DAAcABAABAAIAAwADAAAAGgAAAAcAAAAFAAAAAMAAAAAAAAAAAAAAAQABAAEAAAABAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAABoAAAAAAAAAIAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAGgAAAAAA' +
  'AAAAAAAAAgAAAAMAAAAAAAAAAAAAAAAAAAADAAAAAAAAAAAAAAAAAAAAAwAAAAAAAAAEIk0YYECC' +
  'AwAAgAABAgAAAAAAAAAAAAADAAAAAAAAAAQiTRhgQIIDAACAAAECAAAAAAAAAAAAAP////8AAAAA';

/** Decode a base64 capture into the raw Arrow IPC stream bytes. */
export function captureBytes(base64: string): Uint8Array {
  return Uint8Array.from(Buffer.from(base64, 'base64'));
}
