/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

/**
 * `rayfin env` — emit a framework-specific `.env.local` from the
 * `RAYFIN_PUBLIC_*` subset of `rayfin/.env`.
 *
 * See docs/rfc/env-file-strategy.md § Frontend Integration.
 */

import { mkdir, writeFile } from 'fs/promises';
import { isAbsolute, join, relative, resolve } from 'path';

import {
  mapPublicEnvForFramework,
  serializeEnvContent,
  type FrontendFramework,
} from '@microsoft/rayfin-tools-common/_internal/config';
import { Command, Option } from 'commander';

import { loadRayfinConfig } from '../../utils/config-utils.js';
import { readEnvMap } from '../../utils/env-file-utils.js';
import { detectFrontendFramework } from '../../utils/frontend-detect.js';
import { findRayfinProjectRoot } from '../../utils/project-utils.js';

const SUPPORTED_FRAMEWORKS: readonly FrontendFramework[] = [
  'vite',
  'nextjs',
  'plain',
];

interface WriteOptions {
  projectRoot: string;
  framework: FrontendFramework;
  /** Relative (from project root) or absolute directory for `.env.local`. */
  outputDir: string;
}

/**
 * Build the framework-mapped `.env.local` content from `rayfin/.env` and
 * write it to `<outputDir>/.env.local`.
 *
 * @returns The absolute path that was written.
 */
export async function writeFrameworkEnvFile(
  options: WriteOptions
): Promise<string> {
  const { projectRoot, framework, outputDir } = options;

  const rayfinDir = join(projectRoot, 'rayfin');
  const envVars = await readEnvMap(rayfinDir);
  const mapped = mapPublicEnvForFramework(envVars, framework);

  const header = [
    'Auto-generated by `rayfin env` from rayfin/.env — do not edit.',
    `Regenerate with: rayfin env --framework ${framework}`,
  ];

  const outputAbs = isAbsolute(outputDir)
    ? outputDir
    : resolve(projectRoot, outputDir);
  await mkdir(outputAbs, { recursive: true });
  const filePath = join(outputAbs, '.env.local');
  const content = serializeEnvContent(mapped, header);
  await writeFile(filePath, content, 'utf8');
  return filePath;
}

export const envCommand = new Command('env')
  .description(
    'Emit framework-specific .env.local from rayfin/.env (RAYFIN_PUBLIC_* only)'
  )
  .addOption(
    new Option(
      '--framework <framework>',
      'Target framework: vite, nextjs, or plain. Auto-detected from package.json if omitted'
    ).choices([...SUPPORTED_FRAMEWORKS])
  )
  .option(
    '--output <dir>',
    'Directory for .env.local, relative to project root. Default: project root'
  )
  .option(
    '--show',
    'Print resolved public variables to stdout and exit without writing'
  )
  .action(
    async (options: {
      framework?: FrontendFramework;
      output?: string;
      show?: boolean;
    }) => {
      let projectRoot: string;
      try {
        projectRoot = findRayfinProjectRoot(process.cwd());
      } catch {
        console.error('❌ Not inside a Rayfin project (no `rayfin/` folder).');
        process.exit(1);
      }

      const framework =
        options.framework ?? detectFrontendFramework(projectRoot) ?? undefined;

      if (options.show) {
        const rayfinDir = join(projectRoot, 'rayfin');
        const envVars = await readEnvMap(rayfinDir);
        const target: FrontendFramework = framework ?? 'plain';
        const mapped = mapPublicEnvForFramework(envVars, target);
        if (mapped.size === 0) {
          console.log('(no RAYFIN_PUBLIC_* variables found in rayfin/.env)');
          return;
        }
        console.log(
          `Resolved RAYFIN_PUBLIC_* variables (framework: ${target}):`
        );
        for (const [k, v] of mapped) {
          console.log(`  ${k}=${v}`);
        }
        return;
      }

      if (!framework) {
        console.error(
          '❌ No framework detected. Pass --framework <vite|nextjs|plain>.'
        );
        process.exit(1);
      }

      // Prefer explicit --output; otherwise default to static hosting service
      // path when configured so workspace frontends receive `.env.local` in
      // the correct package directory.
      const config = loadRayfinConfig(projectRoot, { silent: true });
      const outputDir =
        options.output ?? config?.services.staticHosting?.path ?? '.';
      const filePath = await writeFrameworkEnvFile({
        projectRoot,
        framework,
        outputDir,
      });
      const displayPath = relative(process.cwd(), filePath) || filePath;
      console.log(`✅ ${framework} detected — wrote ${displayPath}.`);
    }
  );
