export {
  ConnectorsError,
  createConnectorsApi,
  DEFAULT_HOST_ENVIRONMENT,
  detectHost,
  SemanticConnectorClient,
  GraphQLConnectorClient,
} from './Connectors';

export type { ConnectorEntityClient } from './category-a/ConnectorEntityClient';

export type {
  DbOperationResult,
  InstanceOf,
  MutationResult,
  PrimaryKeyOf,
  WhereUniqueOf,
} from './category-a/types';

/**
 * `Source()` connector base-class factory and the `AutoGenerated<T>` server-
 * generated-column marker. Their canonical public home is this package —
 * `Source` is connector-only, so it lives with the connector clients rather
 * than in `@microsoft/rayfin-core`.
 */
export { Source } from './category-a/schema/source';
export type {
  SourceOptions,
  RayfinPrimaryKeyCarrier,
} from './category-a/schema/source';
export * from './category-a/schema/auto-generated';

export type {
  ConnectorRuntime,
  ConnectorsRuntime,
  HostEnvironment,
  InvokeContext,
  InvokeHttpClient,
  InvokeNext,
  OperationRuntime,
  TypedConnectorsApi,
} from './Connectors';

export {
  METHODS_FOR_CRUD_OPERATION,
  isConnectorError,
} from './ConnectorsSchema';

/**
 * Re-exported so consumers (and the connector type surface in
 * `@microsoft/rayfin-connector-fabric-graphql`) can name the primary-key
 * phantom that `PrimaryKeyOf`/`WhereUniqueOf` read, without depending on
 * `@microsoft/rayfin-core` directly.
 */
export { RayfinPrimaryKey } from '@microsoft/rayfin-core';

export type {
  ConnectorConfig,
  ConnectorError,
  ConnectorErrorCategory,
  ConnectorErrorResult,
  ConnectorMarker,
  ConnectorType,
  ConnectorsSchema,
  CrudOperation,
  InvokeOptions,
  OperationCatalog,
  OperationDef,
  TypedConnectorClient,
} from './ConnectorsSchema';
