import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';

import {
  loadRayfinConfig,
  readSecretNames,
  validateServicePath,
} from './config-utils.js';
import { findRayfinProjectRoot } from './project-utils.js';

/**
 * Default location of the generated augmentation, relative to the project
 * root, used when `services.functions.path` is not set in `rayfin.yml`.
 *
 * It lives under the functions `src/` tree because that is what the functions
 * `tsconfig.json` includes, and being part of the compilation is the only thing
 * a module augmentation needs — nothing imports this file. It is deliberately
 * *not* under `rayfin/data/`, which is shared with the frontend and has no
 * business knowing about the functions SDK.
 */
export const SECRETS_TYPES_RELATIVE_PATH =
  'rayfin/functions/src/secrets.generated.ts';

/**
 * Default location of the functions package, kept in sync with
 * `DEFAULT_FUNCTIONS_PATH` in `commands/functions/functions-init.ts`.
 */
const DEFAULT_FUNCTIONS_PATH = 'rayfin/functions';

/**
 * Basename of the generated file.
 *
 * The functions typegen watcher watches `src/` recursively, so it must ignore
 * this file for the same reason it ignores `types.ts`: regenerating it inside
 * the watched tree would otherwise re-trigger the watcher.
 */
export const SECRETS_TYPES_FILENAME = 'secrets.generated.ts';

/** The package whose `RayfinSecretRegistry` interface is augmented. */
export const SECRETS_MODULE_SPECIFIER = '@microsoft/fabric-user-data-functions';

export interface GenerateSecretsTypesResult {
  status: 'written' | 'unchanged' | 'skipped';
  reason?: 'project-root-not-found';
  /** Absolute path of the generated file, when one was resolved. */
  outputPath?: string;
  /** Secret names baked into the registry, sorted. */
  secretNames?: string[];
}

/**
 * Render the generated module.
 *
 * With no secrets the augmentation block is omitted entirely, leaving
 * `RayfinSecretRegistry` empty — which makes `ctx.Secrets` an empty object type
 * and any property access a compile error. That is the correct state for an app
 * that has not declared any, and it is why the file is still emitted rather
 * than deleted: its presence shows generation ran.
 */
function renderSecretsModule(secretNames: string[]): string {
  const header = `/**
 * Secret names declared in rayfin.yml.
 *
 * AUTO-GENERATED — do not edit manually.
 * Regenerated by \`rayfin secret set\`, \`rayfin secret delete\`, and whenever
 * function types are generated.
 *
 * This file augments the SDK's \`RayfinSecretRegistry\`, which is what types
 * \`ctx.Secrets\` in every function:
 *
 *   udf.func('charge', async (ctx: RayfinContext<AppSchema>) => {
 *     ctx.Secrets.MY_SECRET;   // string
 *     ctx.Secrets.NOT_THERE;   // compile error
 *   });
 *
 * Nothing imports this file — it only needs to be part of the compilation,
 * which the functions tsconfig's \`src\` include already guarantees.
 *
 * Only names appear here. Secret values are supplied per invocation and are
 * never written to disk.
 */
`;

  if (secretNames.length === 0) {
    return `${header}
// No secrets are declared in rayfin.yml, so the registry stays empty and
// ctx.Secrets exposes nothing.

export {};
`;
  }

  const properties = secretNames
    .map((name) => `    ${name}: string;`)
    .join('\n');

  return `${header}
declare module '${SECRETS_MODULE_SPECIFIER}' {
  interface RayfinSecretRegistry {
${properties}
  }
}

export {};
`;
}

/**
 * Generate the secrets registry augmentation from the `secrets:` list in
 * `rayfin.yml`.
 *
 * The registry is the single source of truth for secret names, so a function
 * never spells one out as a string literal: adding or removing a secret changes
 * the type, and any stale reference stops compiling.
 *
 * The augmentation is written under the *resolved* functions package —
 * `services.functions.path` in `rayfin.yml` when set (e.g. `packages/functions`
 * in an npm-workspace layout), otherwise the `rayfin/functions` default.
 * Ignoring that config previously left a stray `rayfin/functions/` directory
 * behind on every workspace-layout project, even though the real functions
 * package lived elsewhere.
 *
 * Writes only when the content actually changes, so the file does not churn on
 * every dev-server rebuild.
 */
export function generateSecretsTypes(
  startPath: string = process.cwd()
): GenerateSecretsTypesResult {
  let projectRoot: string;
  try {
    projectRoot = findRayfinProjectRoot(startPath, {
      verbose: false,
      silent: true,
    });
  } catch {
    return { status: 'skipped', reason: 'project-root-not-found' };
  }

  // Sorted so the generated file is stable regardless of the order secrets were
  // added to rayfin.yml.
  const secretNames = [...readSecretNames(projectRoot)].sort();

  const config = loadRayfinConfig(projectRoot, { silent: true });
  const configuredPath = config?.services?.functions?.path;
  const functionsPath =
    typeof configuredPath === 'string' && configuredPath.trim() !== ''
      ? configuredPath
      : DEFAULT_FUNCTIONS_PATH;
  // The directory may not exist yet (e.g. `secret set` run before `functions
  // init`), so only guard against path traversal — not existence.
  //
  // Take the resolved path from the validator rather than re-resolving
  // `functionsPath`: validation normalises both slash styles, so a
  // Windows-authored `path: 'packages\functions'` would otherwise be written to
  // `<root>/packages\functions/src/` on POSIX — a literal directory named
  // `packages\functions` — while generation still reported success and the real
  // functions package never saw the updated types.
  const functionsDir = validateServicePath(
    projectRoot,
    'functions',
    functionsPath,
    { requireExists: false }
  );
  const outputPath = join(functionsDir, 'src', SECRETS_TYPES_FILENAME);
  const contents = renderSecretsModule(secretNames);

  if (existsSync(outputPath)) {
    const current = readFileSync(outputPath, 'utf-8');
    if (current === contents) {
      return { status: 'unchanged', outputPath, secretNames };
    }
  }

  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, contents, 'utf-8');
  return { status: 'written', outputPath, secretNames };
}

/**
 * Generate the registry ahead of a functions build, best-effort.
 *
 * Every path that compiles the functions project — `functions init`,
 * `rayfin dev`, `rayfin dev functions apply`, and deployment — builds *before*
 * {@link generateFunctionsTypes} runs. A project with a secret declared in
 * `rayfin.yml` but no `secrets.generated.ts` yet (a fresh clone, a first
 * `functions init`, or a `secret set` made from another machine) therefore
 * fails the build with `TS2339: Property 'API_KEY' does not exist` and exits
 * before the generator it needs is ever reached.
 *
 * Unlike {@link generateSecretsTypes} this never throws. It runs before the
 * build purely so the file exists; the authoritative call inside
 * `generateFunctionsTypes` still surfaces a misconfigured
 * `services.functions.path`, and a build should not start failing for a reason
 * unrelated to the user's code.
 *
 * @param functionsDir - The functions project directory. The project root is
 *   found by walking up from here.
 * @param onWarn - Optional sink for the failure reason; defaults to silence
 *   because the authoritative call reports it.
 */
export function ensureSecretsTypes(
  functionsDir: string,
  onWarn?: (message: string) => void
): GenerateSecretsTypesResult | undefined {
  try {
    return generateSecretsTypes(functionsDir);
  } catch (error) {
    onWarn?.(
      `Could not generate ${SECRETS_TYPES_FILENAME}: ${
        error instanceof Error ? error.message : String(error)
      }`
    );
    return undefined;
  }
}
