import { describe, it, expectTypeOf } from 'vitest';

import type {
  AutoGenerated,
  IsAutoGenerated,
  ReadRecord,
  UnwrapAutoGenerated,
} from '../category-a/schema/auto-generated';

describe('AutoGenerated marker', () => {
  it('brands the underlying type (plain T is not assignable, branded T is usable as T)', () => {
    // A branded value is still a usable T (assignable to the base type).
    expectTypeOf<AutoGenerated<number>>().toMatchTypeOf<number>();
    // A plain T is NOT assignable to the branded type — this is what lets the
    // connector input types detect a marked column.
    expectTypeOf<number>().not.toMatchTypeOf<AutoGenerated<number>>();
  });

  it('unwraps back to plain T', () => {
    expectTypeOf<
      UnwrapAutoGenerated<AutoGenerated<number>>
    >().toEqualTypeOf<number>();
    expectTypeOf<
      UnwrapAutoGenerated<AutoGenerated<string>>
    >().toEqualTypeOf<string>();
    // Plain (unbranded) types pass through unchanged.
    expectTypeOf<UnwrapAutoGenerated<boolean>>().toEqualTypeOf<boolean>();
  });

  it('is detected by IsAutoGenerated; plain and `any` are not', () => {
    expectTypeOf<
      IsAutoGenerated<AutoGenerated<number>>
    >().toEqualTypeOf<true>();
    expectTypeOf<IsAutoGenerated<number>>().toEqualTypeOf<false>();
    expectTypeOf<IsAutoGenerated<any>>().toEqualTypeOf<false>();
  });

  it('expresses nullability on the property, not inside the marker', () => {
    // The generator brands the non-null base type and carries nullability on the
    // optional `?` property; `ReadRecord` unwraps the marker and the `?`
    // survives as `T | undefined`.
    type Row = {
      id: AutoGenerated<number>;
      lineTotal?: AutoGenerated<number>;
    };
    expectTypeOf<ReadRecord<Row>>().toEqualTypeOf<{
      id: number;
      lineTotal?: number;
    }>();
  });
});
