/**
 * @packageDocumentation Type-level tests for {@link ConnectorEntityClient}'s
 * read/by-key selection surface.
 *
 * These assert the compile-time contract that the connector `_by_pk` and read
 * paths can actually honor:
 *  - `findByKey(where, select)` takes **scalar** columns only (a relationship
 *    or a dotted path is not a leaf the `_by_pk` builder can emit) and its
 *    return type tracks the projection (`Pick<Row, select[number]>`).
 *  - `select([...])` accepts scalar columns and **dotted** relationship paths
 *    (`reading.severity`), which the query builder expands to a nested
 *    `reading` selection, but rejects the **bare** relationship name
 *    (`reading`), which would emit an invalid leaf the server rejects.
 *
 * Run under Vitest's `typecheck` mode (see `vitest.config.ts`): a missing error
 * on a `@ts-expect-error` line — or a wrong inferred type — fails the suite.
 * The client-referencing expressions are wrapped in never-called arrows so the
 * bodies are type-checked without executing (the client is a `declare const`
 * with no runtime value).
 */

import { RayfinPrimaryKey } from '@microsoft/rayfin-core';
import { describe, it, expectTypeOf } from 'vitest';

import { ConnectorEntityClient } from '../category-a/ConnectorEntityClient';
import type { AutoGenerated } from '../category-a/schema/auto-generated';
import type { WhereUniqueOf } from '../category-a/types';

/** A related entity (navigation target) with its own scalar columns. */
class Reading {
  sensorId!: number;
  severity!: string;
}

/** Composite-key entity with scalar columns, an optional scalar, and a relationship. */
class Alert {
  static readonly [RayfinPrimaryKey] = ['sensorId', 'alertSeq'] as const;
  sensorId!: number;
  alertSeq!: number;
  severity!: string;
  note?: string;
  reading?: Reading;
}

/**
 * Entity mixing `AutoGenerated<T>` scalar columns (a server-generated key and a
 * defaulted column) with a plain scalar FK and a relationship — the shape that
 * exercises `CreateInput`'s relationship exclusion without misclassifying a
 * *branded* scalar (`number & Tag`, which structurally extends `object`) as a
 * relationship.
 */
class Order {
  static readonly [RayfinPrimaryKey] = ['id'] as const;
  id!: AutoGenerated<number>;
  customerId!: number;
  quantity!: AutoGenerated<number>;
  payload?: Buffer;
  customer?: Reading;
}

type OrderSchema = { Order: typeof Order };
declare const orderClient: ConnectorEntityClient<OrderSchema, 'Order'>;

type Schema = { Alert: typeof Alert };

declare const client: ConnectorEntityClient<Schema, 'Alert'>;
declare const key: { sensorId: number; alertSeq: number };

/**
 * Self-referential entity with **two** relationships pointing at its own type
 * (`parent` to-one, `childUnits` to-many). This is the shape that made the old
 * path-*enumerating* selection type explode into a "union too complex to
 * represent" error (~2^depth cross-product). The validator-based type must walk
 * only the segments actually written, so deep paths compile with no blow-up.
 */
class OrgUnit {
  static readonly [RayfinPrimaryKey] = ['orgId', 'unitId'] as const;
  orgId!: number;
  unitId!: number;
  unitName!: string;
  parent?: OrgUnit;
  childUnits?: OrgUnit[];
}

type OrgSchema = { OrgUnit: typeof OrgUnit };
declare const orgClient: ConnectorEntityClient<OrgSchema, 'OrgUnit'>;

describe('ConnectorEntityClient.select — selection narrowing', () => {
  it('accepts scalar columns (required and optional)', () => {
    expectTypeOf(() =>
      client.select(['sensorId', 'alertSeq', 'severity', 'note'])
    ).toBeFunction();
  });

  it('accepts dotted relationship paths', () => {
    expectTypeOf(() =>
      client.select(['severity', 'reading.severity', 'reading.sensorId'])
    ).toBeFunction();
  });

  it('rejects a bare relationship name', () => {
    expectTypeOf(() => {
      // @ts-expect-error 'reading' is a relationship object, not a selectable leaf.
      client.select(['reading']);
    }).toBeFunction();
  });

  it('rejects an unknown column', () => {
    expectTypeOf(() => {
      // @ts-expect-error 'nope' is not a column of Alert.
      client.select(['nope']);
    }).toBeFunction();
  });
});

describe('ConnectorEntityClient.select — deep paths on self-referential entities', () => {
  it('accepts deeply nested relationship paths without a union blow-up', () => {
    expectTypeOf(() =>
      orgClient.select([
        'orgId',
        'unitName',
        'parent.unitName',
        'parent.parent.parent.parent.orgId',
        'childUnits.parent.childUnits.unitName',
      ])
    ).toBeFunction();
  });

  it('rejects a bare self-relationship name', () => {
    expectTypeOf(() => {
      // @ts-expect-error 'parent' is a relationship object, not a selectable leaf.
      orgClient.select(['parent']);
    }).toBeFunction();
  });

  it('rejects an invalid segment part-way down a deep path', () => {
    expectTypeOf(() => {
      // @ts-expect-error 'nope' is not a field of OrgUnit at that hop.
      orgClient.select(['parent.parent.nope.orgId']);
    }).toBeFunction();
  });
});

describe('ConnectorEntityClient.select — constraint survives the builder chain', () => {
  it('accepts a deep path on a where-first select', () => {
    expectTypeOf(() =>
      orgClient.where({ orgId: { eq: 1 } }).select(['parent.parent.orgId'])
    ).toBeFunction();
  });

  it('rejects a bare relationship on a where-first select', () => {
    expectTypeOf(() => {
      // @ts-expect-error 'parent' is a relationship, not a selectable leaf.
      orgClient.where({ orgId: { eq: 1 } }).select(['parent']);
    }).toBeFunction();
  });

  it('rejects a bad mid-path segment on a chained select', () => {
    expectTypeOf(() => {
      // @ts-expect-error 'nope' is not a field of OrgUnit at that hop.
      orgClient.select(['orgId']).select(['parent.nope.orgId']);
    }).toBeFunction();
  });
});

describe('ConnectorEntityClient.findMany / findFirst — optional select', () => {
  it('accepts scalar columns and dotted paths, with an optional filter', () => {
    expectTypeOf(() =>
      client.findMany(['sensorId', 'severity', 'reading.severity'])
    ).toBeFunction();
    expectTypeOf(() =>
      client.findFirst(['severity'], { severity: { eq: 'high' } })
    ).toBeFunction();
  });

  it('returns the full row when the select argument is omitted', () => {
    expectTypeOf(() => client.findMany()).returns.resolves.toEqualTypeOf<
      Alert[]
    >();
    expectTypeOf(() =>
      client.findFirst()
    ).returns.resolves.toEqualTypeOf<Alert | null>();
  });

  it('accepts a filter as the first argument (no selection)', () => {
    expectTypeOf(() =>
      client.findMany({ severity: { eq: 'high' } })
    ).returns.resolves.toEqualTypeOf<Alert[]>();
    expectTypeOf(() =>
      client.findFirst({ severity: { eq: 'high' } })
    ).returns.resolves.toEqualTypeOf<Alert | null>();
  });

  it('rejects a bare relationship name in the select', () => {
    expectTypeOf(() => {
      // @ts-expect-error 'reading' is a relationship object, not a selectable leaf.
      client.findMany(['reading']);
    }).toBeFunction();
  });
});

describe('ConnectorEntityClient.findByKey — scalar select + projection-tracked return', () => {
  it('tracks the projection in the return type', () => {
    expectTypeOf(() =>
      client.findByKey(key, ['severity', 'note'])
    ).returns.resolves.toEqualTypeOf<Pick<Alert, 'severity' | 'note'> | null>();
  });

  it('narrows the return type to exactly the selected column', () => {
    expectTypeOf(() =>
      client.findByKey(key, ['severity'])
    ).returns.resolves.toEqualTypeOf<Pick<Alert, 'severity'> | null>();
  });

  it('returns the full row when select is omitted', () => {
    expectTypeOf(() =>
      client.findByKey(key)
    ).returns.resolves.toEqualTypeOf<Alert | null>();
  });

  it('rejects a bare relationship column', () => {
    expectTypeOf(() => {
      // @ts-expect-error 'reading' is not a scalar column.
      client.findByKey(key, ['reading']);
    }).toBeFunction();
  });

  it('rejects a dotted relationship path', () => {
    expectTypeOf(() => {
      // @ts-expect-error 'reading.severity' is not a scalar column of Alert.
      client.findByKey(key, ['reading.severity']);
    }).toBeFunction();
  });

  it('rejects an unknown column', () => {
    expectTypeOf(() => {
      // @ts-expect-error 'nope' is not a column of Alert.
      client.findByKey(key, ['nope']);
    }).toBeFunction();
  });

  it('accepts a Buffer (binary) scalar column as a projection', () => {
    // `payload` is a `Buffer` column; it must be selectable like any scalar.
    expectTypeOf(() =>
      orderClient.findByKey({ id: 1 }, ['payload'])
    ).toBeFunction();
  });
});

describe('ConnectorEntityClient.create — CreateInput excludes relationship fields', () => {
  it('accepts scalar columns without the relationship navigation object', () => {
    // `reading` is a relationship on Alert; a create supplies only scalar
    // columns (the composite key + `severity`), never a nested entity object.
    expectTypeOf(() =>
      client.create({ sensorId: 1, alertSeq: 2, severity: 'high' })
    ).toBeFunction();
  });

  it('allows omitting an optional scalar column', () => {
    expectTypeOf(() =>
      client.create({ sensorId: 1, alertSeq: 2, severity: 'high', note: 'x' })
    ).toBeFunction();
  });

  it('rejects a relationship navigation object in the create input', () => {
    expectTypeOf(() => {
      client.create({
        sensorId: 1,
        alertSeq: 2,
        severity: 'high',
        // @ts-expect-error 'reading' is a relationship, not a create column.
        reading: { sensorId: 1, severity: 'high' },
      });
    }).toBeFunction();
  });

  it('still requires the scalar columns (a relationship is not a substitute)', () => {
    expectTypeOf(() => {
      // @ts-expect-error missing required scalar 'severity'.
      client.create({ sensorId: 1, alertSeq: 2 });
    }).toBeFunction();
  });

  it('keeps AutoGenerated scalar columns (a branded scalar is not a relationship)', () => {
    // `id` and `quantity` are AutoGenerated<number> (branded scalars). They must
    // remain in the input as optional — not be dropped as relationships — while
    // the plain scalar FK `customerId` stays required.
    expectTypeOf(() => orderClient.create({ customerId: 1 })).toBeFunction();
    expectTypeOf(() =>
      orderClient.create({ customerId: 1, id: 5, quantity: 3 })
    ).toBeFunction();
  });

  it('excludes the relationship but requires the scalar FK on an AutoGenerated entity', () => {
    expectTypeOf(() => {
      orderClient.create({
        customerId: 1,
        // @ts-expect-error 'customer' is a relationship, not a create column.
        customer: { sensorId: 1, severity: 'high' },
      });
    }).toBeFunction();
    expectTypeOf(() => {
      // @ts-expect-error missing required scalar 'customerId'.
      orderClient.create({ id: 5 });
    }).toBeFunction();
  });

  it('keeps a Buffer (binary) scalar column — not misclassified as a relationship', () => {
    // `Buffer` is an object-typed Rayfin scalar; it must stay a create column.
    expectTypeOf(() =>
      orderClient.create({ customerId: 1, payload: Buffer.from('x') })
    ).toBeFunction();
  });
});

describe('ConnectorEntityClient.update — UpdateInput excludes relationship fields', () => {
  it('accepts a subset of scalar columns (every column is optional)', () => {
    expectTypeOf(() => client.update(key, { severity: 'high' })).toBeFunction();
    expectTypeOf(() => client.update(key, {})).toBeFunction();
  });

  it('keeps AutoGenerated scalar columns as optional (a branded scalar is not a relationship)', () => {
    // `id` and `quantity` are AutoGenerated<number> (branded scalars). They stay
    // in the update input as optional plain values — not dropped as relationships.
    expectTypeOf(() =>
      orderClient.update({ id: 5 }, { quantity: 3, customerId: 1 })
    ).toBeFunction();
  });

  it('keeps a Buffer (binary) scalar column — not misclassified as a relationship', () => {
    expectTypeOf(() =>
      orderClient.update({ id: 5 }, { payload: Buffer.from('x') })
    ).toBeFunction();
  });

  it('rejects a relationship navigation object in the update input', () => {
    expectTypeOf(() => {
      client.update(key, {
        severity: 'high',
        // @ts-expect-error 'reading' is a relationship, not an update column.
        reading: { sensorId: 1, severity: 'high' },
      });
    }).toBeFunction();
    expectTypeOf(() => {
      orderClient.update(
        { id: 5 },
        {
          // @ts-expect-error 'customer' is a relationship, not an update column.
          customer: { sensorId: 1, severity: 'high' },
        }
      );
    }).toBeFunction();
  });
});

describe('WhereUniqueOf — branded PK diagnostics', () => {
  it('brands an optional PK column with an actionable message', () => {
    class OptionalPkAlert {
      static readonly [RayfinPrimaryKey] = ['note'] as const;
      note?: string;
    }
    expectTypeOf<
      WhereUniqueOf<typeof OptionalPkAlert>
    >().toEqualTypeOf<"Primary key column 'note' is declared optional; primary key columns must be NOT NULL. Remove the '?' or drop it from Source({ primaryKey }).">();
  });

  it('brands a relationship PK column with an actionable message', () => {
    class RelationPkAlert {
      static readonly [RayfinPrimaryKey] = ['reading'] as const;
      reading?: Reading;
    }
    expectTypeOf<
      WhereUniqueOf<typeof RelationPkAlert>
    >().toEqualTypeOf<"Primary key column 'reading' is a relationship field, not a scalar column.">();
  });
});

describe('ConnectorEntityClient aggregation surface', () => {
  it('exposes a chainable groupBy → aggregate → execute path', () => {
    expectTypeOf(() =>
      client
        .groupBy(['severity'])
        .aggregate({ total: { sum: 'sensorId' } })
        .execute()
    ).returns.resolves.toEqualTypeOf<
      { fields: { severity: string }; aggregations: { total: number | null } }[]
    >();
  });

  it('exposes a grand-total aggregate → execute path', () => {
    expectTypeOf(() =>
      client.aggregate({ total: { sum: 'sensorId' } }).execute()
    ).returns.resolves.toEqualTypeOf<
      { fields: {}; aggregations: { total: number | null } }[]
    >();
  });

  it('rejects grouping by an unknown column', () => {
    expectTypeOf(() => {
      // @ts-expect-error 'nope' is not a column of Alert.
      client.groupBy(['nope']);
    }).toBeFunction();
  });

  it('rejects aggregating a non-scalar relationship field', () => {
    expectTypeOf(() => {
      // @ts-expect-error 'reading' is a relationship, not a numeric scalar.
      client.aggregate({ total: { sum: 'reading' } });
    }).toBeFunction();
  });
});
