/**
 * Public export-boundary regression test for `@microsoft/rayfin-connectors`.
 *
 * `Source` (runtime) and the `AutoGenerated<T>` type machinery moved into this
 * package and are the canonical public API here. Consumers import them from the
 * package entry point, so this test pins that barrel surface: every name is
 * imported through `../index` (the built `@microsoft/rayfin-connectors` entry),
 * not the internal `category-a/schema/*` modules the other suites use. If a
 * re-export in `index.ts` is dropped, this suite fails — the internal-path
 * tests would stay green and let the break ship silently.
 */

import { describe, expect, expectTypeOf, it } from 'vitest';

import { Source } from '../index';
import type {
  AutoGenerated,
  AutoGeneratedKeys,
  AutoGeneratedTag,
  IsAutoGenerated,
  RayfinPrimaryKeyCarrier,
  ReadRecord,
  SourceOptions,
  UnwrapAutoGenerated,
} from '../index';

type Assert<T extends true> = T;

/** Runtime (value) exports of the package entry point. */
type PublicValueExports = keyof typeof import('../index');

/** `Source` must stay a runtime export of `@microsoft/rayfin-connectors`. */
export type SourceIsPubliclyExported = Assert<
  'Source' extends PublicValueExports ? true : false
>;

/**
 * The `AutoGenerated` type machinery (and the `Source` companion types) must
 * stay importable from the entry point. Each reference fails to compile if the
 * barrel drops the corresponding re-export, so vitest's typecheck pass guards
 * the type surface.
 */
export type PublicTypeExportsAreAvailable = [
  AutoGenerated<number>,
  AutoGeneratedTag<number>,
  AutoGeneratedKeys<{ id: AutoGenerated<number> }>,
  IsAutoGenerated<AutoGenerated<number>>,
  ReadRecord<{ id: AutoGenerated<number> }>,
  UnwrapAutoGenerated<AutoGenerated<number>>,
  SourceOptions<readonly ['id']>,
  RayfinPrimaryKeyCarrier<readonly ['id']>,
];

describe('@microsoft/rayfin-connectors public export boundary', () => {
  it('exports Source as a runtime value from the package entry point', () => {
    expect(typeof Source).toBe('function');
  });

  it('Source() produces a constructable connector base class', () => {
    const Base = Source({
      schema: 'dbo',
      table: 'Product',
      primaryKey: ['id'],
    });
    expect(typeof Base).toBe('function');
  });

  it('keeps Source on the package value-export surface', () => {
    expectTypeOf<'Source'>().toExtend<PublicValueExports>();
  });

  it('exposes the AutoGenerated type machinery through the entry point', () => {
    expectTypeOf<
      UnwrapAutoGenerated<AutoGenerated<number>>
    >().toEqualTypeOf<number>();
    expectTypeOf<
      IsAutoGenerated<AutoGenerated<number>>
    >().toEqualTypeOf<true>();
  });
});
