/**
 * Connector type surface: primary-key derivation, read-selection types
 * (including deep relationship paths), and create / update / result shapes for
 * {@link ConnectorEntityClient}. Types only — no runtime footprint.
 */

import { RayfinPrimaryKey } from '@microsoft/rayfin-core';
import type { Scalars } from '@microsoft/rayfin-core';
import type { EntitySchema, CleanEntityKeys } from '@microsoft/rayfin-data';
import {
  Connector,
  type ConnectorType,
} from '@microsoft/rayfin-tools-common/_internal/config';

import type { ConnectorGraphQLQueryBuilder } from './ConnectorGraphQLQueryBuilder';
import type {
  ReadRecord,
  IsAutoGenerated,
  UnwrapAutoGenerated,
} from './schema/auto-generated';

/** Connector type (writes, but no read-after-write) whose mutations return {@link DbOperationResult}. */
type NoReadAfterWriteConnectorType = typeof Connector.FabricWarehouse;

/** Result returned by a connector without read-after-write, in place of the row. */
export interface DbOperationResult {
  readonly result: string;
}

/**
 * Return type of a create/update/delete: the entity row, or
 * {@link DbOperationResult} for dialects without read-after-write.
 */
export type MutationResult<TDialect extends ConnectorType, TRecord> = [
  TDialect,
] extends [NoReadAfterWriteConnectorType]
  ? DbOperationResult
  : TRecord;

// ===========================================================================
// Primary-key derivation from the entity's static RayfinPrimaryKey phantom.
// No `id` fallback: a by-key surface exists only when a non-empty primaryKey
// tuple is declared.
// ===========================================================================

/** Instance (record) type of a schema entry, whether it is a constructor or a bare instance type. */
export type InstanceOf<T> = T extends abstract new (
  ...args: infer _Args
) => infer I
  ? I
  : T;

/**
 * The **unwrapped row** type for a schema entry: its {@link InstanceOf} with
 * every `AutoGenerated<…>` column reduced to plain `T`. This is what reads,
 * filters, ordering, and mutation results speak in — a server-generated column
 * (identity / default / computed) reads back as plain `T`, never "maybe
 * branded". The branded {@link InstanceOf} is retained only where the brand is
 * load-bearing: {@link CreateInput} (to detect which columns are optional on
 * insert) and the primary-key derivation.
 */
export type Row<T> = ReadRecord<InstanceOf<T>>;

/**
 * Ordered primary-key tuple from the entity's static {@link RayfinPrimaryKey}
 * phantom; empty tuple (keyless) when the phantom is absent or not a string tuple.
 */
export type PrimaryKeyOf<T> = T extends {
  readonly [RayfinPrimaryKey]: infer PK;
}
  ? PK extends readonly string[]
    ? PK
    : readonly []
  : readonly [];

/** Keys of `O` that carry the optional `?` modifier. */
type OptionalKeysOf<O> = {
  [K in keyof O]-?: {} extends Pick<O, K> ? K : never;
}[keyof O];

/** Value types a scalar primary-key column may have (relationships are objects). Mirrors core's `Scalars` (which includes object-typed `Date`/`Buffer`) plus `bigint`. */
type ScalarColumn = Scalars | bigint;

/** Scalar (non-relationship) column names of `I`, including optional scalar columns. */
export type ScalarColumnsOf<I> = Extract<
  {
    [K in keyof I]: NonNullable<I[K]> extends ScalarColumn ? K : never;
  }[keyof I],
  string
>;

// ===========================================================================
// Read selection: scalar columns plus deep relationship paths. A relationship
// field is selectable only as a dotted path, never a bare leaf. Each written
// path is validated (recursion depth = path length), so deep paths type-check
// on cyclic relationship graphs without union blow-up.
// ===========================================================================

/** Whether `V` is a relationship value (entity object or array of entity objects) rather than a scalar. Every supported scalar (object-typed `Date`/`Buffer`, and `bigint`) counts as scalar via {@link ScalarColumn}. */
type IsRelationship<V> =
  NonNullable<V> extends ScalarColumn
    ? false
    : NonNullable<V> extends readonly (infer U)[]
      ? NonNullable<U> extends ScalarColumn
        ? false
        : NonNullable<U> extends object
          ? true
          : false
      : NonNullable<V> extends object
        ? true
        : false;

/** The singular entity a relationship value points at (array element, or the object itself). */
type RelatedEntity<V> =
  NonNullable<V> extends readonly (infer U)[] ? U : NonNullable<V>;

/** Scalar (leaf-selectable) column names of `T` — the complement of its relationship fields. */
type ScalarLeafKeys<T> = {
  [K in CleanEntityKeys<T> & string]: IsRelationship<T[K]> extends true
    ? never
    : K;
}[CleanEntityKeys<T> & string];

/** Relationship (navigation) field names of `T` — the complement of its scalar columns. */
type RelationshipKeys<T> = Exclude<
  CleanEntityKeys<T> & string,
  ScalarLeafKeys<T>
>;

/** Decrement ladder bounding {@link ConnectorPathHint} recursion; index `0` is guarded before it is read. */
type PrevDepth = [never, 0, 1, 2, 3, 4, 5];

/**
 * Autocomplete surface for entity `T`: a flat union of its scalar columns and
 * relationship paths enumerated to relationship depth `D`. Depth-capped so
 * cyclic relationships don't recurse infinitely; emits only finite literals
 * (never an open template, which TypeScript won't surface as a completion).
 */
type ConnectorPathHint<T, D extends number = 2> =
  | ScalarLeafKeys<T>
  | {
      [R in RelationshipKeys<T>]: D extends 0
        ? `${R}.`
        :
            | `${R}.`
            | `${R}.${ConnectorPathHint<
                RelatedEntity<T[R & keyof T]>,
                PrevDepth[D]
              >}`;
    }[RelationshipKeys<T>];

/**
 * Validate a dotted selection path `P` against entity `T`, resolving to `P`
 * when legal and to a hint type otherwise. A dotted head must be a relationship
 * (recurse into the related entity) and the final segment a scalar leaf; a bare
 * relationship name is rejected.
 */
type ValidConnectorPath<
  T,
  P extends string,
> = P extends `${infer Head}.${infer Tail}`
  ? Head extends RelationshipKeys<T>
    ? `${Head}.${ValidConnectorPath<RelatedEntity<T[Head & keyof T]>, Tail>}`
    : ConnectorPathHint<T>
  : ConnectorPathHint<T>;

/** Selectable field set for a read: a tuple whose every element is a validated scalar column or dotted relationship path. */
export type ConnectorFieldSelection<T, F extends readonly string[]> = {
  readonly [I in keyof F]: ValidConnectorPath<T, F[I]>;
};

/** Declared key columns that resolve to a real field on the instance. */
type ResolvedPkColumns<T> = Extract<
  PrimaryKeyOf<T>[number],
  keyof InstanceOf<T>
>;

/** Declared key columns that are relationship (navigation) fields, not scalar columns. */
type RelationshipPkColumns<T> = {
  [K in ResolvedPkColumns<T>]: NonNullable<
    InstanceOf<T>[K]
  > extends ScalarColumn
    ? never
    : K;
}[ResolvedPkColumns<T>];

/** Declared key columns that are optional/nullable on the instance. */
type OptionalPkColumns<T> = Extract<
  ResolvedPkColumns<T>,
  OptionalKeysOf<InstanceOf<T>>
>;

/**
 * Branded diagnostic for an invalid primary-key column, or `never` when valid.
 * Key columns must be scalar and NOT NULL; relationship is reported before
 * optional. The literal surfaces the error at the call site.
 */
type InvalidPkError<T> = [RelationshipPkColumns<T>] extends [never]
  ? [OptionalPkColumns<T>] extends [never]
    ? never
    : `Primary key column '${OptionalPkColumns<T> & string}' is declared optional; primary key columns must be NOT NULL. Remove the '?' or drop it from Source({ primaryKey }).`
  : `Primary key column '${RelationshipPkColumns<T> & string}' is a relationship field, not a scalar column.`;

/** Replace a shape with the PK diagnostic when the key is invalid, else pass it through. */
export type GuardInvalidPk<T, TShape> = [InvalidPkError<T>] extends [never]
  ? TShape
  : InvalidPkError<T>;

/**
 * By-key `where` shape: an exact `Pick` over the declared key columns. A keyless
 * entry resolves to `never` (by-key update/delete uncallable). A key that
 * doesn't resolve to a real field collapses to `never`; a relationship or
 * optional key column resolves to an `InvalidPkError`.
 */
export type WhereUniqueOf<T> =
  PrimaryKeyOf<T> extends readonly []
    ? never
    : [Exclude<PrimaryKeyOf<T>[number], keyof InstanceOf<T>>] extends [never]
      ? GuardInvalidPk<T, ReadRecord<Pick<InstanceOf<T>, ResolvedPkColumns<T>>>>
      : never;

/**
 * Column values accepted when creating a row.
 *
 * A DAB connector record is a flat set of scalar columns — including any
 * foreign-key columns (e.g. `sensorId`), which are plain scalars on the record,
 * not nested entity objects. Create takes exactly the record's scalar columns,
 * with two transforms driven by the `AutoGenerated<T>` marker:
 *
 * - **Server-generated columns are optional.** A column the database fills in —
 *   `IDENTITY`, any `DEFAULT` (literal or expression), or a computed column —
 *   is marked `AutoGenerated<T>` by the entity author; here it becomes optional
 *   so the caller may omit it and let the server supply the value. This holds
 *   even for a primary-key column with a server default
 *   (e.g. `id UNIQUEIDENTIFIER DEFAULT NEWID()`), which is required in
 *   {@link WhereUniqueOf} (by-key) yet optional here (on insert).
 * - **Every value is unwrapped.** Marked or not, each column's value type is
 *   {@link UnwrapAutoGenerated | unwrapped} to plain `T`, so callers pass plain
 *   values (`{ id: 123 }`), never a branded type they cannot construct.
 *
 * **Relationship (navigation) fields are excluded.** A `@one`/`@many` property
 * is not a column on the flat record — the row is created by supplying the
 * scalar foreign-key column(s) it maps to, never a nested entity object. Such
 * fields are dropped from the input regardless of their declared optionality
 * (`!` or `?`), so a required navigation property never forces the caller to
 * pass an entity object.
 *
 * Non-generated columns keep the record's own optionality: a column the record
 * marks optional/nullable (`col?:`) stays optional, required columns stay
 * required. Detection is fail-closed — only a column the marker unambiguously
 * flags is relaxed to optional (see {@link IsAutoGenerated}).
 */
export type CreateInput<TRecord> = {
  [K in keyof TRecord as IsRelationship<
    UnwrapAutoGenerated<TRecord[K]>
  > extends true
    ? never
    : IsAutoGenerated<TRecord[K]> extends true
      ? never
      : K]: UnwrapAutoGenerated<TRecord[K]>;
} & {
  [K in keyof TRecord as IsRelationship<
    UnwrapAutoGenerated<TRecord[K]>
  > extends true
    ? never
    : IsAutoGenerated<TRecord[K]> extends true
      ? K
      : never]?: UnwrapAutoGenerated<TRecord[K]>;
};

/**
 * Column values accepted when updating a row: any subset of the record's
 * scalar columns, each unwrapped to plain `T` (a server-generated column reads
 * and writes as plain `T`). `@one`/`@many` navigation fields are excluded
 * regardless of optionality — an update sets scalar/foreign-key columns, never
 * a nested entity object. The target row is identified by the by-key `where`
 * argument, so the key columns need not (and should not) be repeated here.
 */
export type UpdateInput<TRecord> = {
  [K in keyof TRecord as IsRelationship<
    UnwrapAutoGenerated<TRecord[K]>
  > extends true
    ? never
    : K]?: UnwrapAutoGenerated<TRecord[K]>;
};

/** Read query-builder for entity `E` in schema `S`, keyed by the unwrapped {@link Row} type so `execute()` yields plain rows. */
export type BuilderFor<
  S extends EntitySchema,
  E extends keyof S,
> = ConnectorGraphQLQueryBuilder<Record<E, Row<S[E]>>, E>;
