import { expect } from 'vitest';

/**
 * Normalizes a GraphQL query string by removing extra whitespace and newlines
 * for consistent comparison between expected and actual queries.
 *
 * @param query - The GraphQL query string to normalize
 * @returns Normalized query string with consistent spacing
 */
export function normalizeQuery(query: string): string {
  return query.replace(/\s+/g, ' ').replace(/\n/g, ' ').trim();
}

/**
 * Formats a GraphQL query string for better readability in console output.
 * Adds proper indentation and line breaks for debugging purposes.
 *
 * @param query - The GraphQL query string to format
 * @returns Pretty-formatted query string
 */
export function formatQuery(query: string): string {
  return query
    .replace(/{\s*/g, '{\n  ')
    .replace(/}\s*/g, '\n}')
    .replace(/,\s*/g, ',\n  ')
    .replace(/query\s*{/g, 'query {\n  ')
    .replace(/items\s*{/g, 'items {\n    ')
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line.length > 0)
    .join('\n');
}

/**
 * Compares two GraphQL query strings and provides detailed diff output on failure.
 * Uses normalized comparison for accuracy while showing formatted queries for debugging.
 *
 * @param actual - The actual query string generated by the builder
 * @param expected - The expected query string
 * @throws `AssertionError` if queries don't match
 */
export function compareQueries(actual: string, expected: string): void {
  const normalizedActual = normalizeQuery(actual);
  const normalizedExpected = normalizeQuery(expected);

  if (normalizedActual !== normalizedExpected) {
    console.log('\n=== QUERY COMPARISON FAILED ===');
    console.log('\nEXPECTED:');
    console.log(formatQuery(expected));
    console.log('\nACTUAL:');
    console.log(formatQuery(actual));
    console.log('\n=== NORMALIZED COMPARISON ===');
    console.log('\nEXPECTED (normalized):');
    console.log(normalizedExpected);
    console.log('\nACTUAL (normalized):');
    console.log(normalizedActual);
    console.log('\n=================================');
  }

  expect(normalizedActual).toBe(normalizedExpected);
}

/**
 * Validates DAB-specific compliance requirements in a GraphQL query string.
 * Checks for proper boolean serialization, entity naming, enum formatting, etc.
 *
 * @param query - The GraphQL query string to validate
 * @param isMutation - Whether this is a mutation (singular entity names) or query (plural entity names)
 */
export function validateDABCompliance(query: string, isMutation = false): void {
  if (isMutation) {
    // Mutation entity naming should singular with operation prefix
    expect(query).toMatch(/\b(create|update|delete)[a-zA-Z]+\(/); // lowercase singular entity name pattern
  } else {
    // Query entity naming should be plural; allow arg-less queries ending with '{'
    expect(query).toMatch(/\b[a-zA-Z]+s(\(|\s*{)/); // plural entity name pattern
    // Example:
    //     query {
    //   todos {
    //     items {
    //       id
    //     }
    //   }
    // }
  }

  // Boolean values should be unquoted
  if (query.includes('eq: true') || query.includes('eq: false')) {
    expect(query).toMatch(/eq: (true|false)/);
    expect(query).not.toMatch(/eq: "(true|false)"/);
  }

  // Boolean values in mutation inputs should NOT be quoted strings
  if (
    query.includes('isCompleted: true') ||
    query.includes('isCompleted: false')
  ) {
    expect(query).toMatch(/isCompleted: (true|false)/);
  }

  // Enum values (ASC/DESC) should not be quoted
  if (query.includes('ASC') || query.includes('DESC')) {
    expect(query).not.toContain('"ASC"');
    expect(query).not.toContain('"DESC"');
  }

  // Cursor values should be quoted strings
  if (query.includes('after:') || query.includes('before:')) {
    expect(query).toMatch(/(after|before): "[^"]+"/);
  }
}
