import {
  app,
  HttpRequest,
  HttpResponseInit,
  InvocationContext,
  input,
  FunctionInput,
} from '@azure/functions';

import {
  UserDataFunctionInternalError,
  UserDataFunctionInvalidInputError,
  UserDataFunctionMissingInputError,
} from './errors/udfErrors.js';
import { tryConvert } from './internal/addParameters.js';
import { ensureFormattedReturnType } from './internal/ensureFormattedReturnType.js';
import { decode } from './internal/fabricItemConverter.js';
import { runWithInvocationLogging } from './internal/logger.js';
import {
  loadRuntimeMetadata,
  MINIMUM_RUNTIME_METADATA_SCHEMA_VERSION,
  resolveRuntimeMetadataPath,
  type RuntimeDelegateParameterMetadata,
  type RuntimeFunctionMetadata,
  type RuntimeMetadataLoadResult,
} from './runtimeMetadata.js';
import { AUDIENCE_SCOPE_OVERRIDES } from './types/audienceScopes.js';
import {
  AudienceType,
  Connection,
  type AliasConnectionOptions,
  type AnyConnection,
  type ConnectionOptions,
  type GenericConnectionOptions,
} from './types/connection.js';
import { RayfinContext } from './types/rayfinContext.js';

/** Returns true if the parsed type string refers to `RayfinContext` (with or without a generic). */
function isRayfinContextType(type?: string): boolean {
  if (!type) return false;
  return type === 'RayfinContext' || type.startsWith('RayfinContext<');
}

/**
 * Split the outermost type-argument list of `Name<A, B, C>` into its
 * top-level arguments, without the TypeScript compiler.
 *
 * Only used to decide whether an annotation declares audiences at all, so it
 * does not need to understand the arguments themselves — just where they start
 * and end. Nested brackets, `=>` and string literals are skipped.
 */
function splitTopLevelTypeArguments(type: string): string[] {
  const open = type.indexOf('<');
  if (open < 0) return [];

  const args: string[] = [];
  let depth = 0;
  let start = open + 1;
  let quote: string | null = null;

  for (let i = open + 1; i < type.length; i++) {
    const ch = type[i];
    if (quote) {
      if (ch === quote && type[i - 1] !== '\\') quote = null;
      continue;
    }
    if (ch === "'" || ch === '"' || ch === '`') {
      quote = ch;
    } else if (ch === '<' || ch === '(' || ch === '[' || ch === '{') {
      depth++;
    } else if (ch === '>' && type[i - 1] === '=') {
      // Arrow in a function type, not a closing bracket.
    } else if (ch === '>' || ch === ')' || ch === ']' || ch === '}') {
      if (depth === 0) {
        args.push(type.slice(start, i));
        return args;
      }
      depth--;
    } else if (ch === ',' && depth === 0) {
      args.push(type.slice(start, i));
      start = i + 1;
    }
  }

  // Unterminated list: keep what is there so the caller errs towards
  // "declares audiences" rather than silently binding nothing.
  args.push(type.slice(start));
  return args;
}

/**
 * True when a `RayfinContext` annotation has a non-`never` audience argument,
 * i.e. its audiences matter and must come from somewhere.
 */
function declaresContextAudiences(type?: string): boolean {
  if (!isRayfinContextType(type)) return false;
  const audienceArgument = splitTopLevelTypeArguments(type!)[1]?.trim();
  return (
    audienceArgument !== undefined &&
    audienceArgument.length > 0 &&
    audienceArgument !== 'never'
  );
}

/**
 * First function whose metadata lacks `contextAudiences` but whose context
 * annotation declares audiences — metadata written by a CLI that predates the
 * field. Its audiences can then only be recovered by parsing annotation text.
 */
function findFunctionNeedingTypeTextAudiences(
  functions: readonly RuntimeFunctionMetadata[]
): string | undefined {
  return functions.find(
    (entry) =>
      entry.contextAudiences === undefined &&
      entry.delegateParameters.some((parameter) =>
        declaresContextAudiences(parameter.type)
      )
  )?.functionName;
}

function describeMissingContextAudiences(
  functionName: string,
  metadataPath: string
): string {
  return (
    `Runtime metadata at '${metadataPath}' does not record the audiences function '${functionName}' declares on its RayfinContext annotation. ` +
    `It was generated by a Rayfin CLI that predates 'contextAudiences'.`
  );
}

type UnusableRuntimeMetadata = Exclude<
  RuntimeMetadataLoadResult,
  { status: 'valid' }
>;

/**
 * Category of metadata failure reported back to callers.
 *
 * This is deliberately a closed set of tokens rather than a message: it is the
 * only part of the failure that crosses the invoke boundary, so it must not
 * carry the metadata path or any other detail about the host's filesystem
 * layout. The full explanation goes to the logs instead.
 */
export type MetadataErrorReason =
  | 'missing'
  | 'invalid'
  | 'unsupported-version'
  | 'legacy-metadata';

/** Failure state captured at construction: a safe token plus a log-only detail. */
interface MetadataFailure {
  reason: MetadataErrorReason;
  diagnostic: string;
}

/** Human-readable explanation of why runtime metadata could not be used. */
function describeMetadataProblem(
  result: UnusableRuntimeMetadata,
  metadataPath: string
): string {
  switch (result.status) {
    case 'missing':
      return `Runtime metadata was not found at '${metadataPath}'.`;
    case 'invalid':
      return `Runtime metadata at '${metadataPath}' could not be used. ${result.message}`;
    case 'unsupported-version':
      return (
        `Runtime metadata at '${metadataPath}' declares schema version ` +
        `'${result.version}', but this runtime requires ` +
        `'${MINIMUM_RUNTIME_METADATA_SCHEMA_VERSION}' or newer. ` +
        `Upgrade the Rayfin CLI and redeploy to regenerate it.`
      );
  }
}

/**
 * Message returned to callers when metadata could not be resolved.
 *
 * Deliberately terse and actionable: by the time an invoke reaches a worker in
 * this state the only real remedy is to redeploy from a CLI that matches the
 * runtime, since the CLI is what generates the metadata in the first place.
 */
export const METADATA_UNAVAILABLE_MESSAGE =
  "Unable to determine function metadata. Ensure you're on the latest version " +
  'of the worker runtime and rayfin cli, then try deploying again.';

/**
 * Build the diagnostic logged when metadata cannot be used.
 *
 * The invoke response carries the short, user-facing
 * {@link METADATA_UNAVAILABLE_MESSAGE}; this longer form goes to the logs,
 * where the specific cause and the commands that regenerate metadata are
 * actually useful.
 */
function metadataDiagnostic(problem: string): string {
  return (
    `[UserDataFunctions] ${problem}\n` +
    `Every invocation will fail until this is resolved.\n` +
    `Generate metadata by running 'rayfin dev' or 'rayfin dev functions apply' locally; 'rayfin up' generates it for deployments.`
  );
}

function toParameterMap<T>(
  functions: readonly { functionName: string; delegateParameters: T }[]
): Map<string, T> {
  return new Map(
    functions.map((entry) => [entry.functionName, entry.delegateParameters])
  );
}

/**
 * This class is necessary to define User Data Functions in Fabric.
 * Please ensure an instantiation of this class exists in your code
 * before any User Data Functions are defined.
 *
 * Usage:
 * ```ts
 * import { UserDataFunctions, AudienceType } from "@microsoft/fabric-user-data-functions";
 *
 * const udf = new UserDataFunctions();
 *
 * udf.func("hello", async (name: string) => `Hello ${name}!`);
 *
 * udf.func("syncData", async (ctx: RayfinContext<MySchema, AudienceType.Fabric>) => {
 *   const fabricToken = ctx.Tokens.Fabric;
 * }, []);
 * ```
 */
export class UserDataFunctions {
  private readonly functionParameters: Map<
    string,
    RuntimeDelegateParameterMetadata[]
  >;

  /**
   * Audiences each function declared on its `RayfinContext` annotation, keyed
   * by function name. Populated from runtime metadata, because type arguments
   * do not survive to runtime.
   */
  private readonly functionAudiences: Map<string, string[]>;

  /**
   * Set when runtime metadata could not be resolved, which leaves this
   * instance unable to bind parameters or connections for any function.
   *
   * Construction deliberately does not throw. Throwing here happens while the
   * Azure Functions host is loading `function_app.js`, so the host reports it
   * as "No job functions found" — no routes, and nothing that points at the
   * real cause. Registering the routes and failing each invocation instead
   * means the deployment is reachable and says exactly what is wrong.
   */
  private readonly metadataFailure?: MetadataFailure;

  // TODO: Improve default srcRoot detection — consider using the tsconfig "rootDir",
  // walking up from __dirname, or reading package.json to find the project source root.
  /**
   * Construct from generated runtime metadata.
   *
   * @param srcRoot - The project's TypeScript source root.
   * @param metadataPath - Path to `runtimemetadata.json`; defaults to the file
   *   sitting alongside `srcRoot`.
   *
   * Never throws. When metadata is missing or unusable the instance enters an
   * error state: {@link func} still registers every route, and each invocation
   * fails with {@link METADATA_UNAVAILABLE_MESSAGE}.
   */
  constructor(
    srcRoot = './src',
    metadataPath = resolveRuntimeMetadataPath(srcRoot)
  ) {
    const runtimeMetadata = loadRuntimeMetadata(metadataPath);

    if (runtimeMetadata.status === 'valid') {
      const { functions } = runtimeMetadata.metadata;
      const needsTypeText = findFunctionNeedingTypeTextAudiences(functions);
      if (needsTypeText) {
        // Metadata from a CLI older than this runtime: the audiences exist
        // only as erased annotation text, so the connections these handlers
        // need cannot be bound. Treated as unusable rather than partially
        // applied, since binding some audiences and silently dropping others
        // fails later and further from the cause.
        this.functionParameters = new Map();
        this.functionAudiences = new Map();
        this.metadataFailure = {
          reason: 'legacy-metadata',
          diagnostic: describeMissingContextAudiences(
            needsTypeText,
            metadataPath
          ),
        };
        console.error(metadataDiagnostic(this.metadataFailure.diagnostic));
        return;
      }
      this.functionParameters = toParameterMap(functions);
      this.functionAudiences =
        UserDataFunctions.resolveMetadataAudiences(functions);
      return;
    }

    this.functionParameters = new Map();
    this.functionAudiences = new Map();
    this.metadataFailure = {
      reason: runtimeMetadata.status,
      diagnostic: describeMetadataProblem(runtimeMetadata, metadataPath),
    };
    console.error(metadataDiagnostic(this.metadataFailure.diagnostic));
  }

  /**
   * Construct from generated runtime metadata.
   *
   * @param srcRoot - The project's TypeScript source root.
   * @param metadataPath - Path to `runtimemetadata.json`; defaults to the file
   *   sitting alongside `srcRoot`.
   *
   * @deprecated Construction is synchronous again now that no resolution path
   *   needs a dynamic import. Use `new UserDataFunctions()` directly; this
   *   remains so existing `await UserDataFunctions.create()` call sites keep
   *   working.
   */
  static async create(
    srcRoot = './src',
    metadataPath = resolveRuntimeMetadataPath(srcRoot)
  ): Promise<UserDataFunctions> {
    return new UserDataFunctions(srcRoot, metadataPath);
  }

  /**
   * Audiences each function declared on its `RayfinContext` annotation, keyed
   * by function name.
   *
   * Type arguments are erased before this runs, so the CLI resolves them with
   * its type checker at build time and writes the result to
   * `functions[].contextAudiences`. Reading that field is the only path;
   * metadata that predates it is rejected by the caller.
   *
   * Names are validated against {@link AudienceType}: anything unrecognised
   * means the two ends have drifted, and it is reported rather than silently
   * registering a binding for an audience that does not exist.
   */
  private static resolveMetadataAudiences(
    functions: readonly RuntimeFunctionMetadata[]
  ): Map<string, string[]> {
    const knownAudiences = new Set<string>(Object.values(AudienceType));

    return new Map(
      functions.map((entry) => {
        const audiences: string[] = [];
        for (const candidate of entry.contextAudiences ?? []) {
          if (!knownAudiences.has(candidate)) {
            console.warn(
              `[UserDataFunctions] Function '${entry.functionName}': '${candidate}' in the RayfinContext annotation is not an AudienceType member, so no connection was bound for it. Declare audiences literally, e.g. RayfinContext<Schema, AudienceType.Sql>.`
            );
            continue;
          }
          if (!audiences.includes(candidate)) audiences.push(candidate);
        }
        return [entry.functionName, audiences];
      })
    );
  }

  /**
   * Create a connection declaration for use with `func()`.
   *
   * Overloaded so that alias connections resolve to `Connection<never>`.
   * Without the split, `TokenType` has no inference site for an alias-shaped
   * argument and falls back to its constraint — making an alias connection look
   * like it declares *every* audience.
   *
   * @param options - Either `{ alias, argName? }` for managed Fabric connections
   *   or `{ audienceType }` for generic audience-scoped access tokens.
   */
  connection<TokenType extends AudienceType>(
    options: GenericConnectionOptions<TokenType>
  ): Connection<TokenType>;
  connection(options: AliasConnectionOptions): Connection<never>;
  connection<TokenType extends AudienceType>(
    options: ConnectionOptions<TokenType>
  ): Connection<TokenType> {
    return new Connection(options);
  }

  /**
   * Register a User Data Function.
   *
   * Generic connections are declared on the handler's context annotation; the
   * audience union in `RayfinContext<Schema, Audiences>` is what determines
   * which resource-scoped tokens the function binds:
   *
   * ```ts
   * udf.func(
   *   'myFunc',
   *   async (ctx: RayfinContext<DataModel, AudienceType.Sql | AudienceType.ADO>) => {
   *     ctx.Tokens.AzureAI;  // compile error — not declared
   *     ctx.Tokens.ADO; // ok
   *     const sqlToken: string = ctx.Tokens.Sql;
   *   }
   * );
   * ```
   *
   * The audiences are recovered at build time and written into
   * `runtimemetadata.json`, because type arguments are erased before this runs.
   * The CLI substitutes the union its type checker resolved, so an audience
   * declared through a type alias still binds.
   *
   * `connections` remains for compatibility. Generic connections passed there
   * are unioned with the annotated audiences and still bind at **runtime**,
   * but they carry no type information: `TokenTypes` defaults to `never`, so a
   * handler annotated `RayfinContext<Schema>` cannot call `getToken` for an
   * audience declared only in the array. Source compatibility requires moving
   * the audience into the annotation.
   *
   * NOTE: the context parameter must carry an explicit `RayfinContext<...>`
   * annotation. Typegen identifies it from the annotation's source text
   * (see `isRayfinContextType`), so an unannotated parameter is treated as a
   * request-body parameter at runtime.
   *
   * @param name - The function name (becomes the HTTP route).
   * @param fn - The user's async handler.
   * @param connections - Optional alias connections (and, for compatibility,
   *   generic ones).
   */
  /**
   * Register a route that reports the metadata failure instead of invoking the
   * handler.
   *
   * The route is registered with no bindings, since the audiences each handler
   * needs are exactly what could not be determined. Requests are answered
   * through the normal response envelope so callers parse the failure the same
   * way they parse any other, which maps to HTTP 500.
   *
   * `reason` carries only the failure category. The metadata path stays in the
   * logged diagnostic: `properties` is serialized into the invoke response, so
   * anything put here is handed to every caller.
   */
  private registerMetadataErrorRoute(name: string): void {
    app.http(name, {
      methods: ['POST'],
      authLevel: 'anonymous',
      handler: async (
        _request: HttpRequest,
        context: InvocationContext
      ): Promise<HttpResponseInit> =>
        runWithInvocationLogging(context, async () =>
          ensureFormattedReturnType(
            () => {
              throw new UserDataFunctionInternalError(
                METADATA_UNAVAILABLE_MESSAGE,
                { reason: this.metadataFailure?.reason ?? 'invalid' }
              );
            },
            name,
            context.invocationId,
            context
          )
        ),
    });
  }

  func(
    name: string,
    fn: (...args: any[]) => any,
    connections?: readonly AnyConnection[]
  ): void {
    if (this.metadataFailure !== undefined) {
      this.registerMetadataErrorRoute(name);
      return;
    }

    const delegateParams = this.functionParameters.get(name) ?? [];

    // Names of params declared as RayfinContext — these read from headers/env, not bindings.
    const rayfinParamNames = new Set(
      delegateParams
        .filter((p) => isRayfinContextType(p.type))
        .map((p) => p.name)
    );

    // Build bindings for generic audience-based connections.
    const genericBindings: FunctionInput[] = [];
    // Build bindings for alias-based connections (managed Fabric items).
    const connectionBindings = new Map<string, FunctionInput>();

    const seenAudiences = new Set<string>();
    const addGenericBinding = (audienceType: string): void => {
      if (seenAudiences.has(audienceType)) return;
      seenAudiences.add(audienceType);
      const scopeOverride =
        AUDIENCE_SCOPE_OVERRIDES[audienceType as AudienceType];
      genericBindings.push(
        input.generic({
          type: 'FabricItem',
          audienceType,
          // For audiences not yet natively supported by the host, specify the scope explicitly.
          ...(scopeOverride && { audienceScope: scopeOverride }),
          // Synthetic name required by the Azure Functions binding framework (every binding
          // must have a name for gRPC serialization to the host). The host extension doesn't
          // use this value for generic connections — it routes on audienceType instead.
          argName: `__generic_${audienceType}`,
        })
      );
    };

    // Audiences declared on the handler's RayfinContext annotation. This is the
    // primary declaration site; type arguments are erased, so they arrive via
    // build-time metadata rather than from the `connections` argument.
    for (const audienceType of this.functionAudiences.get(name) ?? []) {
      addGenericBinding(audienceType);
    }

    if (connections) {
      for (const conn of connections) {
        if (conn.isGeneric) {
          // Generic connections in the array remain supported and are unioned
          // with the annotated audiences.
          addGenericBinding(conn.audienceType!);
        } else {
          if (rayfinParamNames.has(conn.argName!)) continue;
          connectionBindings.set(
            conn.argName!,
            input.generic({
              type: 'FabricItem',
              alias: conn.alias,
              argName: conn.argName,
            })
          );
        }
      }
    }

    // required to register the bindings
    const extraInputs = [...connectionBindings.values(), ...genericBindings];

    app.http(name, {
      methods: ['POST'],
      authLevel: 'anonymous',
      extraInputs,
      handler: async (
        request: HttpRequest,
        context: InvocationContext
      ): Promise<HttpResponseInit> =>
        runWithInvocationLogging(context, async () => {
          try {
            // Parse body, defaulting to empty object so callers can
            // `invoke()` without passing `{}` when there are no parameters.
            let body: Record<string, unknown> = {};
            try {
              body = (await request.json()) as Record<string, unknown>;
            } catch {
              // Body is empty or not valid JSON — use empty object
            }

            // Build args array — errors are collected as values (not thrown)
            // so all parameter errors can be reported at once.
            const args = delegateParams.map((param) => {
              if (isRayfinContextType(param.type)) {
                const ctxBindingData = genericBindings.map((binding) => ({
                  audienceType: (binding as any).audienceType as string,
                  data: context.extraInputs.get(binding),
                }));
                try {
                  return RayfinContext.fromRequest(request, ctxBindingData);
                } catch (e) {
                  return e instanceof Error ? e : new Error(String(e));
                }
              }

              if (param.isFabricParameter) {
                const binding = connectionBindings.get(param.name);
                if (!binding) {
                  return new UserDataFunctionInvalidInputError(
                    `No connection binding found for fabric parameter '${param.name}'. Ensure a Connection with alias and argName '${param.name}' is passed in the connections array.`
                  );
                }
                const bindingData = context.extraInputs.get(binding);
                return decode(bindingData);
              }

              // Non FabricItem parameter — resolve from body with type conversion
              if (param.name in body) {
                const rawParamValue = body[param.name];
                return param.type
                  ? tryConvert(rawParamValue, param.type, param.name)
                  : rawParamValue;
              } else if (param.hasDefault) {
                return undefined;
              } else {
                return new UserDataFunctionMissingInputError(
                  'Parameter not found in the request',
                  {
                    parameter_name: param.name,
                    parameter_value: 'Parameter not found in request',
                  }
                );
              }
            });

            return ensureFormattedReturnType(
              async () => fn(...args),
              name,
              context.invocationId,
              context,
              args
            );
          } catch (error) {
            console.error(
              `[UserDataFunctions] Unhandled error in function '${name}' (invocationId='${context.invocationId}').`,
              error
            );
            throw error;
          }
        }),
    });
  }
}
