/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InitializeRouteImport } from './routes/initialize'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsChar123CategoryIdChar125RouteImport } from './routes/products.{-$categoryId}'
import { Route as AuthedProfileRouteImport } from './routes/_authed/profile'
import { Route as AuthedCheckoutRouteImport } from './routes/_authed/checkout'
import { Route as AuthedCartRouteImport } from './routes/_authed/cart'
import { Route as AuthedAdminRouteImport } from './routes/_authed/_admin'
import { Route as AuthedOrdersIndexRouteImport } from './routes/_authed/orders.index'
import { Route as AuthedOrdersOrderIdRouteImport } from './routes/_authed/orders.$orderId'
import { Route as AuthedAdminAdminDashboardRouteImport } from './routes/_authed/_admin/admin/dashboard'
import { Route as AuthedAdminAdminProductsIndexRouteImport } from './routes/_authed/_admin/admin/products.index'
import { Route as AuthedAdminAdminOrdersIndexRouteImport } from './routes/_authed/_admin/admin/orders.index'
import { Route as AuthedAdminAdminCustomersIndexRouteImport } from './routes/_authed/_admin/admin/customers.index'
import { Route as AuthedAdminAdminCategoriesIndexRouteImport } from './routes/_authed/_admin/admin/categories.index'
import { Route as AuthedAdminAdminProductsNewRouteImport } from './routes/_authed/_admin/admin/products.new'
import { Route as AuthedAdminAdminOrdersNewRouteImport } from './routes/_authed/_admin/admin/orders.new'
import { Route as AuthedAdminAdminCategoriesNewRouteImport } from './routes/_authed/_admin/admin/categories.new'
import { Route as AuthedAdminAdminProductsProductIdEditRouteImport } from './routes/_authed/_admin/admin/products.$productId.edit'
import { Route as AuthedAdminAdminOrdersOrderIdEditRouteImport } from './routes/_authed/_admin/admin/orders.$orderId.edit'
import { Route as AuthedAdminAdminCategoriesCategorySlugEditRouteImport } from './routes/_authed/_admin/admin/categories.$categorySlug.edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InitializeRoute = InitializeRouteImport.update({
  id: '/initialize',
  path: '/initialize',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsChar123CategoryIdChar125Route =
  ProductsChar123CategoryIdChar125RouteImport.update({
    id: '/products/{-$categoryId}',
    path: '/products/{-$categoryId}',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthedProfileRoute = AuthedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCheckoutRoute = AuthedCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCartRoute = AuthedCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminRoute = AuthedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOrdersIndexRoute = AuthedOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOrdersOrderIdRoute = AuthedOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminAdminDashboardRoute =
  AuthedAdminAdminDashboardRouteImport.update({
    id: '/admin/dashboard',
    path: '/admin/dashboard',
    getParentRoute: () => AuthedAdminRoute,
  } as any)
const AuthedAdminAdminProductsIndexRoute =
  AuthedAdminAdminProductsIndexRouteImport.update({
    id: '/admin/products/',
    path: '/admin/products/',
    getParentRoute: () => AuthedAdminRoute,
  } as any)
const AuthedAdminAdminOrdersIndexRoute =
  AuthedAdminAdminOrdersIndexRouteImport.update({
    id: '/admin/orders/',
    path: '/admin/orders/',
    getParentRoute: () => AuthedAdminRoute,
  } as any)
const AuthedAdminAdminCustomersIndexRoute =
  AuthedAdminAdminCustomersIndexRouteImport.update({
    id: '/admin/customers/',
    path: '/admin/customers/',
    getParentRoute: () => AuthedAdminRoute,
  } as any)
const AuthedAdminAdminCategoriesIndexRoute =
  AuthedAdminAdminCategoriesIndexRouteImport.update({
    id: '/admin/categories/',
    path: '/admin/categories/',
    getParentRoute: () => AuthedAdminRoute,
  } as any)
const AuthedAdminAdminProductsNewRoute =
  AuthedAdminAdminProductsNewRouteImport.update({
    id: '/admin/products/new',
    path: '/admin/products/new',
    getParentRoute: () => AuthedAdminRoute,
  } as any)
const AuthedAdminAdminOrdersNewRoute =
  AuthedAdminAdminOrdersNewRouteImport.update({
    id: '/admin/orders/new',
    path: '/admin/orders/new',
    getParentRoute: () => AuthedAdminRoute,
  } as any)
const AuthedAdminAdminCategoriesNewRoute =
  AuthedAdminAdminCategoriesNewRouteImport.update({
    id: '/admin/categories/new',
    path: '/admin/categories/new',
    getParentRoute: () => AuthedAdminRoute,
  } as any)
const AuthedAdminAdminProductsProductIdEditRoute =
  AuthedAdminAdminProductsProductIdEditRouteImport.update({
    id: '/admin/products/$productId/edit',
    path: '/admin/products/$productId/edit',
    getParentRoute: () => AuthedAdminRoute,
  } as any)
const AuthedAdminAdminOrdersOrderIdEditRoute =
  AuthedAdminAdminOrdersOrderIdEditRouteImport.update({
    id: '/admin/orders/$orderId/edit',
    path: '/admin/orders/$orderId/edit',
    getParentRoute: () => AuthedAdminRoute,
  } as any)
const AuthedAdminAdminCategoriesCategorySlugEditRoute =
  AuthedAdminAdminCategoriesCategorySlugEditRouteImport.update({
    id: '/admin/categories/$categorySlug/edit',
    path: '/admin/categories/$categorySlug/edit',
    getParentRoute: () => AuthedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/initialize': typeof InitializeRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/cart': typeof AuthedCartRoute
  '/checkout': typeof AuthedCheckoutRoute
  '/profile': typeof AuthedProfileRoute
  '/products/{-$categoryId}': typeof ProductsChar123CategoryIdChar125Route
  '/orders/$orderId': typeof AuthedOrdersOrderIdRoute
  '/orders/': typeof AuthedOrdersIndexRoute
  '/admin/dashboard': typeof AuthedAdminAdminDashboardRoute
  '/admin/categories/new': typeof AuthedAdminAdminCategoriesNewRoute
  '/admin/orders/new': typeof AuthedAdminAdminOrdersNewRoute
  '/admin/products/new': typeof AuthedAdminAdminProductsNewRoute
  '/admin/categories/': typeof AuthedAdminAdminCategoriesIndexRoute
  '/admin/customers/': typeof AuthedAdminAdminCustomersIndexRoute
  '/admin/orders/': typeof AuthedAdminAdminOrdersIndexRoute
  '/admin/products/': typeof AuthedAdminAdminProductsIndexRoute
  '/admin/categories/$categorySlug/edit': typeof AuthedAdminAdminCategoriesCategorySlugEditRoute
  '/admin/orders/$orderId/edit': typeof AuthedAdminAdminOrdersOrderIdEditRoute
  '/admin/products/$productId/edit': typeof AuthedAdminAdminProductsProductIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/initialize': typeof InitializeRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/cart': typeof AuthedCartRoute
  '/checkout': typeof AuthedCheckoutRoute
  '/profile': typeof AuthedProfileRoute
  '/products/{-$categoryId}': typeof ProductsChar123CategoryIdChar125Route
  '/orders/$orderId': typeof AuthedOrdersOrderIdRoute
  '/orders': typeof AuthedOrdersIndexRoute
  '/admin/dashboard': typeof AuthedAdminAdminDashboardRoute
  '/admin/categories/new': typeof AuthedAdminAdminCategoriesNewRoute
  '/admin/orders/new': typeof AuthedAdminAdminOrdersNewRoute
  '/admin/products/new': typeof AuthedAdminAdminProductsNewRoute
  '/admin/categories': typeof AuthedAdminAdminCategoriesIndexRoute
  '/admin/customers': typeof AuthedAdminAdminCustomersIndexRoute
  '/admin/orders': typeof AuthedAdminAdminOrdersIndexRoute
  '/admin/products': typeof AuthedAdminAdminProductsIndexRoute
  '/admin/categories/$categorySlug/edit': typeof AuthedAdminAdminCategoriesCategorySlugEditRoute
  '/admin/orders/$orderId/edit': typeof AuthedAdminAdminOrdersOrderIdEditRoute
  '/admin/products/$productId/edit': typeof AuthedAdminAdminProductsProductIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/initialize': typeof InitializeRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/_authed/_admin': typeof AuthedAdminRouteWithChildren
  '/_authed/cart': typeof AuthedCartRoute
  '/_authed/checkout': typeof AuthedCheckoutRoute
  '/_authed/profile': typeof AuthedProfileRoute
  '/products/{-$categoryId}': typeof ProductsChar123CategoryIdChar125Route
  '/_authed/orders/$orderId': typeof AuthedOrdersOrderIdRoute
  '/_authed/orders/': typeof AuthedOrdersIndexRoute
  '/_authed/_admin/admin/dashboard': typeof AuthedAdminAdminDashboardRoute
  '/_authed/_admin/admin/categories/new': typeof AuthedAdminAdminCategoriesNewRoute
  '/_authed/_admin/admin/orders/new': typeof AuthedAdminAdminOrdersNewRoute
  '/_authed/_admin/admin/products/new': typeof AuthedAdminAdminProductsNewRoute
  '/_authed/_admin/admin/categories/': typeof AuthedAdminAdminCategoriesIndexRoute
  '/_authed/_admin/admin/customers/': typeof AuthedAdminAdminCustomersIndexRoute
  '/_authed/_admin/admin/orders/': typeof AuthedAdminAdminOrdersIndexRoute
  '/_authed/_admin/admin/products/': typeof AuthedAdminAdminProductsIndexRoute
  '/_authed/_admin/admin/categories/$categorySlug/edit': typeof AuthedAdminAdminCategoriesCategorySlugEditRoute
  '/_authed/_admin/admin/orders/$orderId/edit': typeof AuthedAdminAdminOrdersOrderIdEditRoute
  '/_authed/_admin/admin/products/$productId/edit': typeof AuthedAdminAdminProductsProductIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/initialize'
    | '/login'
    | '/logout'
    | '/signup'
    | '/cart'
    | '/checkout'
    | '/profile'
    | '/products/{-$categoryId}'
    | '/orders/$orderId'
    | '/orders/'
    | '/admin/dashboard'
    | '/admin/categories/new'
    | '/admin/orders/new'
    | '/admin/products/new'
    | '/admin/categories/'
    | '/admin/customers/'
    | '/admin/orders/'
    | '/admin/products/'
    | '/admin/categories/$categorySlug/edit'
    | '/admin/orders/$orderId/edit'
    | '/admin/products/$productId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/initialize'
    | '/login'
    | '/logout'
    | '/signup'
    | '/cart'
    | '/checkout'
    | '/profile'
    | '/products/{-$categoryId}'
    | '/orders/$orderId'
    | '/orders'
    | '/admin/dashboard'
    | '/admin/categories/new'
    | '/admin/orders/new'
    | '/admin/products/new'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/categories/$categorySlug/edit'
    | '/admin/orders/$orderId/edit'
    | '/admin/products/$productId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/initialize'
    | '/login'
    | '/logout'
    | '/signup'
    | '/_authed/_admin'
    | '/_authed/cart'
    | '/_authed/checkout'
    | '/_authed/profile'
    | '/products/{-$categoryId}'
    | '/_authed/orders/$orderId'
    | '/_authed/orders/'
    | '/_authed/_admin/admin/dashboard'
    | '/_authed/_admin/admin/categories/new'
    | '/_authed/_admin/admin/orders/new'
    | '/_authed/_admin/admin/products/new'
    | '/_authed/_admin/admin/categories/'
    | '/_authed/_admin/admin/customers/'
    | '/_authed/_admin/admin/orders/'
    | '/_authed/_admin/admin/products/'
    | '/_authed/_admin/admin/categories/$categorySlug/edit'
    | '/_authed/_admin/admin/orders/$orderId/edit'
    | '/_authed/_admin/admin/products/$productId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  InitializeRoute: typeof InitializeRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  SignupRoute: typeof SignupRoute
  ProductsChar123CategoryIdChar125Route: typeof ProductsChar123CategoryIdChar125Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/initialize': {
      id: '/initialize'
      path: '/initialize'
      fullPath: '/initialize'
      preLoaderRoute: typeof InitializeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/{-$categoryId}': {
      id: '/products/{-$categoryId}'
      path: '/products/{-$categoryId}'
      fullPath: '/products/{-$categoryId}'
      preLoaderRoute: typeof ProductsChar123CategoryIdChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/profile': {
      id: '/_authed/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthedProfileRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/checkout': {
      id: '/_authed/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AuthedCheckoutRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/cart': {
      id: '/_authed/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof AuthedCartRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/_admin': {
      id: '/_authed/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedAdminRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/orders/': {
      id: '/_authed/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AuthedOrdersIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/orders/$orderId': {
      id: '/_authed/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof AuthedOrdersOrderIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/_admin/admin/dashboard': {
      id: '/_authed/_admin/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthedAdminAdminDashboardRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/_admin/admin/products/': {
      id: '/_authed/_admin/admin/products/'
      path: '/admin/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AuthedAdminAdminProductsIndexRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/_admin/admin/orders/': {
      id: '/_authed/_admin/admin/orders/'
      path: '/admin/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AuthedAdminAdminOrdersIndexRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/_admin/admin/customers/': {
      id: '/_authed/_admin/admin/customers/'
      path: '/admin/customers'
      fullPath: '/admin/customers/'
      preLoaderRoute: typeof AuthedAdminAdminCustomersIndexRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/_admin/admin/categories/': {
      id: '/_authed/_admin/admin/categories/'
      path: '/admin/categories'
      fullPath: '/admin/categories/'
      preLoaderRoute: typeof AuthedAdminAdminCategoriesIndexRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/_admin/admin/products/new': {
      id: '/_authed/_admin/admin/products/new'
      path: '/admin/products/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AuthedAdminAdminProductsNewRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/_admin/admin/orders/new': {
      id: '/_authed/_admin/admin/orders/new'
      path: '/admin/orders/new'
      fullPath: '/admin/orders/new'
      preLoaderRoute: typeof AuthedAdminAdminOrdersNewRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/_admin/admin/categories/new': {
      id: '/_authed/_admin/admin/categories/new'
      path: '/admin/categories/new'
      fullPath: '/admin/categories/new'
      preLoaderRoute: typeof AuthedAdminAdminCategoriesNewRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/_admin/admin/products/$productId/edit': {
      id: '/_authed/_admin/admin/products/$productId/edit'
      path: '/admin/products/$productId/edit'
      fullPath: '/admin/products/$productId/edit'
      preLoaderRoute: typeof AuthedAdminAdminProductsProductIdEditRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/_admin/admin/orders/$orderId/edit': {
      id: '/_authed/_admin/admin/orders/$orderId/edit'
      path: '/admin/orders/$orderId/edit'
      fullPath: '/admin/orders/$orderId/edit'
      preLoaderRoute: typeof AuthedAdminAdminOrdersOrderIdEditRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/_admin/admin/categories/$categorySlug/edit': {
      id: '/_authed/_admin/admin/categories/$categorySlug/edit'
      path: '/admin/categories/$categorySlug/edit'
      fullPath: '/admin/categories/$categorySlug/edit'
      preLoaderRoute: typeof AuthedAdminAdminCategoriesCategorySlugEditRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
  }
}

interface AuthedAdminRouteChildren {
  AuthedAdminAdminDashboardRoute: typeof AuthedAdminAdminDashboardRoute
  AuthedAdminAdminCategoriesNewRoute: typeof AuthedAdminAdminCategoriesNewRoute
  AuthedAdminAdminOrdersNewRoute: typeof AuthedAdminAdminOrdersNewRoute
  AuthedAdminAdminProductsNewRoute: typeof AuthedAdminAdminProductsNewRoute
  AuthedAdminAdminCategoriesIndexRoute: typeof AuthedAdminAdminCategoriesIndexRoute
  AuthedAdminAdminCustomersIndexRoute: typeof AuthedAdminAdminCustomersIndexRoute
  AuthedAdminAdminOrdersIndexRoute: typeof AuthedAdminAdminOrdersIndexRoute
  AuthedAdminAdminProductsIndexRoute: typeof AuthedAdminAdminProductsIndexRoute
  AuthedAdminAdminCategoriesCategorySlugEditRoute: typeof AuthedAdminAdminCategoriesCategorySlugEditRoute
  AuthedAdminAdminOrdersOrderIdEditRoute: typeof AuthedAdminAdminOrdersOrderIdEditRoute
  AuthedAdminAdminProductsProductIdEditRoute: typeof AuthedAdminAdminProductsProductIdEditRoute
}

const AuthedAdminRouteChildren: AuthedAdminRouteChildren = {
  AuthedAdminAdminDashboardRoute: AuthedAdminAdminDashboardRoute,
  AuthedAdminAdminCategoriesNewRoute: AuthedAdminAdminCategoriesNewRoute,
  AuthedAdminAdminOrdersNewRoute: AuthedAdminAdminOrdersNewRoute,
  AuthedAdminAdminProductsNewRoute: AuthedAdminAdminProductsNewRoute,
  AuthedAdminAdminCategoriesIndexRoute: AuthedAdminAdminCategoriesIndexRoute,
  AuthedAdminAdminCustomersIndexRoute: AuthedAdminAdminCustomersIndexRoute,
  AuthedAdminAdminOrdersIndexRoute: AuthedAdminAdminOrdersIndexRoute,
  AuthedAdminAdminProductsIndexRoute: AuthedAdminAdminProductsIndexRoute,
  AuthedAdminAdminCategoriesCategorySlugEditRoute:
    AuthedAdminAdminCategoriesCategorySlugEditRoute,
  AuthedAdminAdminOrdersOrderIdEditRoute:
    AuthedAdminAdminOrdersOrderIdEditRoute,
  AuthedAdminAdminProductsProductIdEditRoute:
    AuthedAdminAdminProductsProductIdEditRoute,
}

const AuthedAdminRouteWithChildren = AuthedAdminRoute._addFileChildren(
  AuthedAdminRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAdminRoute: typeof AuthedAdminRouteWithChildren
  AuthedCartRoute: typeof AuthedCartRoute
  AuthedCheckoutRoute: typeof AuthedCheckoutRoute
  AuthedProfileRoute: typeof AuthedProfileRoute
  AuthedOrdersOrderIdRoute: typeof AuthedOrdersOrderIdRoute
  AuthedOrdersIndexRoute: typeof AuthedOrdersIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminRoute: AuthedAdminRouteWithChildren,
  AuthedCartRoute: AuthedCartRoute,
  AuthedCheckoutRoute: AuthedCheckoutRoute,
  AuthedProfileRoute: AuthedProfileRoute,
  AuthedOrdersOrderIdRoute: AuthedOrdersOrderIdRoute,
  AuthedOrdersIndexRoute: AuthedOrdersIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  InitializeRoute: InitializeRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  SignupRoute: SignupRoute,
  ProductsChar123CategoryIdChar125Route: ProductsChar123CategoryIdChar125Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
